/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  theme: {
    container: {
      center: true,
      padding: "1.5rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        /* DA Couleurs Imposées */
        blue: {
          50: '#eef7fc',
          100: '#d9edf8',
          200: '#add2e8',
          300: '#82b7d8',
          400: '#5797c2',
          500: '#3d7dac',
          600: '#326795',
          700: '#2b577f',
          800: '#244b80',
          900: '#18375f',
          950: '#08172d',
        },
        violet: {
          50: '#f3f1fb',
          100: '#e8e4f6',
          200: '#d2caed',
          300: '#b5a9df',
          400: '#8b79c8',
          500: '#6150aa',
          600: '#554498',
          700: '#47397f',
          800: '#3b3068',
          900: '#312855',
          950: '#1d1735',
        },
        teal: {
          50: '#edfafd',
          100: '#d5f3f8',
          200: '#afe7f0',
          300: '#7dd5e4',
          400: '#48bdd3',
          500: '#32a5bd',
          600: '#27849b',
          700: '#236b7d',
          800: '#225766',
          900: '#1f4955',
          950: '#0e3039',
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xl: "1rem",
        "2xl": "1.5rem",
        "3xl": "2rem",
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        display: ['Inter', 'system-ui', 'sans-serif'],
      },
      boxShadow: {
        'soft': '0 1px 2px rgba(12, 38, 70, 0.04), 0 10px 30px rgba(12, 38, 70, 0.06)',
        'soft-lg': '0 2px 4px rgba(12, 38, 70, 0.05), 0 20px 50px rgba(12, 38, 70, 0.12)',
        'glow': '0 0 24px rgba(72, 189, 211, 0.24)',
        'glow-violet': '0 0 24px rgba(97, 80, 170, 0.24)',
      },
      keyframes: {
        "accordion-down": {
          from: { height: 0 },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: 0 },
        },
        "fade-in": {
          from: { opacity: 0, transform: "translateY(8px)" },
          to: { opacity: 1, transform: "translateY(0)" },
        },
        "fade-in-up": {
          from: { opacity: 0, transform: "translateY(24px)" },
          to: { opacity: 1, transform: "translateY(0)" },
        },
        "slide-in-left": {
          from: { opacity: 0, transform: "translateX(-20px)" },
          to: { opacity: 1, transform: "translateX(0)" },
        },
        "slide-in-right": {
          from: { opacity: 0, transform: "translateX(20px)" },
          to: { opacity: 1, transform: "translateX(0)" },
        },
        "scale-in": {
          from: { opacity: 0, transform: "scale(0.95)" },
          to: { opacity: 1, transform: "scale(1)" },
        },
        "float": {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-12px)" },
        },
        "pulse-soft": {
          "0%, 100%": { opacity: 1 },
          "50%": { opacity: 0.6 },
        },
        "shimmer": {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
        "slide-up": {
          from: { opacity: 0, transform: "translateY(100%)" },
          to: { opacity: 1, transform: "translateY(0)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.5s ease-out both",
        "fade-in-up": "fade-in-up 0.6s ease-out both",
        "slide-in-left": "slide-in-left 0.5s ease-out both",
        "slide-in-right": "slide-in-right 0.5s ease-out both",
        "scale-in": "scale-in 0.3s ease-out both",
        "float": "float 4s ease-in-out infinite",
        "pulse-soft": "pulse-soft 2.5s ease-in-out infinite",
        "shimmer": "shimmer 2s infinite linear",
        "slide-up": "slide-up 0.4s ease-out both",
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic': 'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
        'gradient-blue-violet': 'linear-gradient(135deg, #6150AA 0%, #48BDD3 100%)',
        'gradient-blue-violet-soft': 'linear-gradient(135deg, rgba(97, 80, 170, 0.12) 0%, rgba(72, 189, 211, 0.1) 100%)',
      },
    },
    typography: {
      DEFAULT: {
        css: {
          '--tw-prose-body': 'hsl(203 55% 85%)',
          '--tw-prose-headings': '#fff',
          '--tw-prose-links': '#48bdd3',
          '--tw-prose-bold': '#fff',
          '--tw-prose-counters': 'hsl(204 25% 65%)',
          '--tw-prose-bullets': 'hsl(204 25% 65%)',
          '--tw-prose-hr': 'rgba(255,255,255,0.1)',
          '--tw-prose-quotes': 'hsl(203 55% 85%)',
          '--tw-prose-quote-borders': '#6150aa',
          '--tw-prose-captions': 'hsl(204 25% 65%)',
          '--tw-prose-code': '#48bdd3',
          '--tw-prose-pre-code': 'hsl(203 55% 90%)',
          '--tw-prose-pre-bg': 'rgba(255,255,255,0.05)',
          '--tw-prose-th-borders': 'rgba(255,255,255,0.15)',
          '--tw-prose-td-borders': 'rgba(255,255,255,0.08)',
          maxWidth: 'none',
          h1: { fontWeight: '900', letterSpacing: '-0.04em' },
          h2: { fontWeight: '800', letterSpacing: '-0.035em' },
          h3: { fontWeight: '700' },
          'ul > li::marker': { color: '#48bdd3' },
          'ol > li::marker': { color: '#48bdd3' },
          a: { fontWeight: '500', textDecoration: 'underline', textDecorationColor: 'rgba(72,189,211,0.4)', textUnderlineOffset: '3px', '&:hover': { color: '#fff', textDecorationColor: '#48bdd3' } },
          blockquote: { borderLeftColor: '#6150aa', fontStyle: 'normal' },
          code: { backgroundColor: 'rgba(255,255,255,0.07)', padding: '0.15em 0.4em', borderRadius: '0.35em', fontWeight: '400' },
          'code::before': { content: 'none' },
          'code::after': { content: 'none' },
          pre: { backgroundColor: 'rgba(255,255,255,0.05)', border: '1px solid rgba(255,255,255,0.08)' },
        },
      },
    },
  },
  plugins: [require("tailwindcss-animate"), require("@tailwindcss/typography")],
}
