<?php

/**
 * Catalogue de traductions AEIC — 7 langues.
 *
 * Structure : ['clé.point' => ['fr' => ..., 'en' => ..., 'de' => ..., 'es' => ..., 'zh' => ..., 'ja' => ..., 'pl' => ...]].
 *
 * Le français est la langue de référence (fallback). Les autres langues
 * peuvent utiliser des marqueurs {n}, {a}, {b}... remplacés dans les vues.
 *
 * Langues : fr, en, de, es, zh, ja, pl.
 */

return [

    /* ----------------------------------------------------------------- */
    /*  Navigation + actions                                             */
    /* ----------------------------------------------------------------- */
    'nav.home'              => ['fr' => 'Accueil', 'en' => 'Home', 'de' => 'Startseite', 'es' => 'Inicio', 'zh' => '首页', 'ja' => 'ホーム', 'pl' => 'Strona główna'],
    'nav.main.aria'         => ['fr' => 'Navigation principale', 'en' => 'Main navigation', 'de' => 'Hauptnavigation', 'es' => 'Navegación principal', 'zh' => '主导航', 'ja' => 'メインナビゲーション', 'pl' => 'Nawigacja główna'],
    'nav.events'            => ['fr' => 'Événements', 'en' => 'Events', 'de' => 'Veranstaltungen', 'es' => 'Eventos', 'zh' => '活动', 'ja' => 'イベント', 'pl' => 'Wydarzenia'],
    'nav.about'             => ['fr' => "L'association", 'en' => 'About', 'de' => 'Über uns', 'es' => 'Asociación', 'zh' => '协会', 'ja' => '协会について', 'pl' => 'O nas'],
    'nav.team'              => ['fr' => 'Équipe', 'en' => 'Team', 'de' => 'Team', 'es' => 'Equipo', 'zh' => '团队', 'ja' => 'チーム', 'pl' => 'Zespół'],
    'nav.polls'             => ['fr' => 'Sondages', 'en' => 'Polls', 'de' => 'Umfragen', 'es' => 'Encuestas', 'zh' => '投票', 'ja' => 'アンケート', 'pl' => 'Ankiety'],
    'nav.gallery'           => ['fr' => 'Galerie', 'en' => 'Gallery', 'de' => 'Galerie', 'es' => 'Galería', 'zh' => '图库', 'ja' => 'ギャラリー', 'pl' => 'Galeria'],
    'nav.login'             => ['fr' => 'Connexion', 'en' => 'Log in', 'de' => 'Anmelden', 'es' => 'Iniciar sesión', 'zh' => '登录', 'ja' => 'ログイン', 'pl' => 'Zaloguj'],
    'nav.register'          => ['fr' => "S'inscrire", 'en' => 'Register', 'de' => 'Registrieren', 'es' => 'Registrarse', 'zh' => '注册', 'ja' => '登録', 'pl' => 'Zarejestruj'],
    'nav.logout'            => ['fr' => 'Déconnexion', 'en' => 'Log out', 'de' => 'Abmelden', 'es' => 'Cerrar sesión', 'zh' => '退出', 'ja' => 'ログアウト', 'pl' => 'Wyloguj'],
    'nav.admin'             => ['fr' => 'Admin', 'en' => 'Admin', 'de' => 'Admin', 'es' => 'Admin', 'zh' => '管理', 'ja' => '管理', 'pl' => 'Admin'],
    'nav.account'           => ['fr' => 'Mon compte', 'en' => 'My account', 'de' => 'Mein Konto', 'es' => 'Mi cuenta', 'zh' => '我的账户', 'ja' => 'アカウント', 'pl' => 'Moje konto'],
    'nav.data'              => ['fr' => 'Mes données', 'en' => 'My data', 'de' => 'Meine Daten', 'es' => 'Mis datos', 'zh' => '我的数据', 'ja' => 'マイデータ', 'pl' => 'Moje dane'],
    'nav.lang.change'       => ['fr' => 'Changer de langue', 'en' => 'Change language', 'de' => 'Sprache ändern', 'es' => 'Cambiar idioma', 'zh' => '切换语言', 'ja' => '言語を変更', 'pl' => 'Zmień język'],
    'nav.theme'             => ['fr' => 'Thème', 'en' => 'Theme', 'de' => 'Design', 'es' => 'Tema', 'zh' => '主题', 'ja' => 'テーマ', 'pl' => 'Motyw'],
    'nav.theme.toggle'      => ['fr' => 'Basculer le thème clair/sombre', 'en' => 'Toggle light/dark theme', 'de' => 'Hell-/Dunkelmodus umschalten', 'es' => 'Alternar tema claro/oscuro', 'zh' => '切换明暗主题', 'ja' => 'テーマを切り替える', 'pl' => 'Przełącz motyw jasny/ciemny'],
    'nav.theme.light.dark'  => ['fr' => 'Thème clair / sombre', 'en' => 'Light / dark theme', 'de' => 'Hell-/Dunkelmodus', 'es' => 'Tema claro / oscuro', 'zh' => '明/暗主题', 'ja' => 'ライト/ダークテーマ', 'pl' => 'Motyw jasny/ciemny'],
    'nav.skip'              => ['fr' => 'Aller au contenu', 'en' => 'Skip to content', 'de' => 'Zum Inhalt', 'es' => 'Ir al contenido', 'zh' => '跳至内容', 'ja' => 'コンテンツへ移動', 'pl' => 'Przejdź do treści'],
    'nav.notifications'     => ['fr' => 'Notifications', 'en' => 'Notifications', 'de' => 'Benachrichtigungen', 'es' => 'Notificaciones', 'zh' => '通知', 'ja' => '通知', 'pl' => 'Powiadomienia'],
    'nav.notifications.empty' => ['fr' => 'Aucune notification.', 'en' => 'No notifications.', 'de' => 'Keine Benachrichtigungen.', 'es' => 'Sin notificaciones.', 'zh' => '暂无通知。', 'ja' => '通知はありません。', 'pl' => 'Brak powiadomień.'],
    'nav.notifications.markall' => ['fr' => 'Tout marquer comme lu', 'en' => 'Mark all as read', 'de' => 'Alle als gelesen markieren', 'es' => 'Marcar todo como leído', 'zh' => '全部标记为已读', 'ja' => 'すべて既読にする', 'pl' => 'Oznacz wszystkie jako przeczytane'],
    'nav.open_menu'         => ['fr' => 'Ouvrir le menu', 'en' => 'Open menu', 'de' => 'Menü öffnen', 'es' => 'Abrir menú', 'zh' => '打开菜单', 'ja' => 'メニューを開く', 'pl' => 'Otwórz menu'],

    /* ----------------------------------------------------------------- */
    /*  Footer                                                           */
    /* ----------------------------------------------------------------- */
    'footer.aria'           => ['fr' => 'Pied de page', 'en' => 'Footer', 'de' => 'Fußzeile', 'es' => 'Pie de página', 'zh' => '页脚', 'ja' => 'フッター', 'pl' => 'Stopka'],
    'footer.tag'            => ['fr' => '100 % étudiant.', 'en' => '100% student-run.', 'de' => '100 % von Studierenden.', 'es' => '100 % estudiantil.', 'zh' => '100% 学生运营。', 'ja' => '100% 学生運営。', 'pl' => '100 % studenckie.'],
    'footer.copy'           => ['fr' => 'Fait par les étudiants, pour les étudiants.', 'en' => 'Made by students, for students.', 'de' => 'Von Studierenden, für Studierende.', 'es' => 'Hecho por estudiantes, para estudiantes.', 'zh' => '由学生打造,为学生服务。', 'ja' => '学生による、学生のための運営。', 'pl' => 'Stworzone przez studentów, dla studentów.'],
    'footer.legal'          => ['fr' => 'Mentions légales', 'en' => 'Legal notice', 'de' => 'Impressum', 'es' => 'Aviso legal', 'zh' => '法律声明', 'ja' => '法的記述', 'pl' => 'Informacje prawne'],
    'footer.privacy'        => ['fr' => 'Confidentialité', 'en' => 'Privacy', 'de' => 'Datenschutz', 'es' => 'Privacidad', 'zh' => '隐私', 'ja' => 'プライバシー', 'pl' => 'Prywatność'],
    'footer.cgu'            => ['fr' => 'CGU', 'en' => 'Terms', 'de' => 'AGB', 'es' => 'Términos', 'zh' => '条款', 'ja' => '利用規約', 'pl' => 'Regulamin'],

    /* ----------------------------------------------------------------- */
    /*  Accueil                                                          */
    /* ----------------------------------------------------------------- */
    'home.eyebrow'          => ['fr' => 'Association étudiante · Informatique · Calais', 'en' => 'Student association · Computer Science · Calais', 'de' => 'Studierendenverein · Informatik · Calais', 'es' => 'Asociación estudiantil · Informática · Calais', 'zh' => '学生社团 · 计算机 · 加来', 'ja' => '学生団体 · 情報科学 · カレー', 'pl' => 'Stowarzyszenie studenckie · Informatyka · Calais'],
    'home.title.line1'      => ['fr' => "Plus qu'une asso.", 'en' => 'More than an association.', 'de' => 'Mehr als ein Verein.', 'es' => 'Más que una asociación.', 'zh' => '不止是一个社团。', 'ja' => '団体以上の存在。', 'pl' => 'Więcej niż stowarzyszenie.'],
    'home.title.line2'      => ['fr' => 'Ton campus, en mieux.', 'en' => 'Your campus, but better.', 'de' => 'Dein Campus, nur besser.', 'es' => 'Tu campus, pero mejor.', 'zh' => '你的校园,更出色。', 'ja' => 'あなたのキャンパス、もっと良く。', 'pl' => 'Twój campus, ale lepszy.'],
    'home.description'      => ['fr' => "L'AEIC réunit les étudiants en informatique du campus de Calais : événements, cafétéria, vie étudiante. Fait par les étudiants, pour les étudiants.", 'en' => 'The AEIC brings together computer science students on the Calais campus: events, cafeteria, student life. Made by students, for students.', 'de' => 'Die AEIC vereint Informatik-Studierende auf dem Campus Calais: Veranstaltungen, Cafeteria, studentisches Leben. Von Studierenden, für Studierende.', 'es' => 'La AEIC reúne a los estudiantes de informática del campus de Calais: eventos, cafetería, vida estudiantil. Hecho por estudiantes, para estudiantes.', 'zh' => 'AEIC 汇聚加来校区的计算机专业学生:活动、咖啡馆、学生生活。由学生打造,为学生服务。', 'ja' => 'AEICはカレーキャンパスの情報科学の学生をまとめます:イベント、カフェテリア、学生生活。学生による、学生のための活動。', 'pl' => 'AEIC łączy studentów informatyki na kampusie w Calais: wydarzenia, kafeteria, życie studenckie. Tworzone przez studentów, dla studentów.'],
    'home.cta.join'         => ['fr' => "Rejoindre l'AEIC", 'en' => 'Join AEIC', 'de' => 'AEIC beitreten', 'es' => 'Únete a la AEIC', 'zh' => '加入 AEIC', 'ja' => 'AEICに参加', 'pl' => 'Dołącz do AEIC'],
    'home.cta.events'       => ['fr' => 'Voir les événements', 'en' => 'See events', 'de' => 'Veranstaltungen ansehen', 'es' => 'Ver eventos', 'zh' => '查看活动', 'ja' => 'イベントを見る', 'pl' => 'Zobacz wydarzenia'],
    'home.features.eyebrow' => ['fr' => "Pourquoi l'AEIC", 'en' => 'Why AEIC', 'de' => 'Warum AEIC', 'es' => 'Por qué la AEIC', 'zh' => '为什么选择 AEIC', 'ja' => 'AEICの魅力', 'pl' => 'Dlaczego AEIC'],
    'home.features.title'   => ['fr' => 'La vie étudiante, sans friction', 'en' => 'Student life, friction-free', 'de' => 'Studierendenleben ohne Reibung', 'es' => 'Vida estudiantil sin fricciones', 'zh' => '无障碍学生生活', 'ja' => '摩擦のない学生生活', 'pl' => 'Życie studenckie bez komplikacji'],
    'home.feature.events.title' => ['fr' => 'Événements', 'en' => 'Events', 'de' => 'Veranstaltungen', 'es' => 'Eventos', 'zh' => '活动', 'ja' => 'イベント', 'pl' => 'Wydarzenia'],
    'home.feature.events.desc' => ['fr' => "Soirées d'intégration, LAN, conférences : un agenda pensé pour les étudiants en info.", 'en' => 'Integration parties, LANs, conferences: an agenda designed for CS students.', 'de' => 'Begrüßungsfeiern, LANs, Konferenzen: ein Terminkalender für Informatik-Studierende.', 'es' => 'Fiestas de integración, LAN, conferencias: una agenda pensada para estudiantes de informática.', 'zh' => '迎新晚会、LAN派对、讲座:专为计算机学生设计的日程。', 'ja' => '新歓、LAN、講演会:情報学生のために作られたスケジュール。', 'pl' => 'Wieczory integracyjne, LAN, konferencje: kalendarz stworzony dla studentów informatyki.'],
    'home.feature.cafeteria.title' => ['fr' => 'Cafétéria', 'en' => 'Cafeteria', 'de' => 'Cafeteria', 'es' => 'Cafetería', 'zh' => '咖啡馆', 'ja' => 'カフェテリア', 'pl' => 'Kafeteria'],
    'home.feature.cafeteria.desc' => ['fr' => 'Des prix étudiant, commandable en ligne, prêt à récupérer entre deux cours.', 'en' => 'Student prices, online ordering, ready to pick up between classes.', 'de' => 'Studierendenpreise, online bestellbar, abholbereit zwischen den Vorlesungen.', 'es' => 'Precios de estudiante, pedidos en línea, listo para recoger entre clases.', 'zh' => '学生价格、在线点餐、课间即可取餐。', 'ja' => '学生価格、オンライン注文、授業の合間に受け取り。', 'pl' => 'Studenckie ceny, zamówienia online, gotowe do odbioru między zajęciami.'],
    'home.feature.community.title' => ['fr' => 'Communauté', 'en' => 'Community', 'de' => 'Community', 'es' => 'Comunidad', 'zh' => '社区', 'ja' => 'コミュニティ', 'pl' => 'Społeczność'],
    'home.feature.community.desc' => ['fr' => "Un réseau d'entraide, des projets, et des gens qui font avancer le campus.", 'en' => 'A support network, projects, and people who move the campus forward.', 'de' => 'Ein Netzwerk für gegenseitige Hilfe, Projekte und Menschen, die den Campus voranbringen.', 'es' => 'Una red de apoyo, proyectos y personas que hacen avanzar el campus.', 'zh' => '互助网络、各类项目,以及推动校园前进的人。', 'ja' => '助け合いのネットワーク、プロジェクト、キャンパスを動かす人々。', 'pl' => 'Sieć wzajemnej pomocy, projekty i ludzie, którzy napędzają kampus.'],
    'home.stat.student'     => ['fr' => 'Étudiant', 'en' => 'Student', 'de' => 'Studierender', 'es' => 'Estudiante', 'zh' => '学生', 'ja' => '学生', 'pl' => 'Student'],
    'home.stat.members'     => ['fr' => 'Membres', 'en' => 'Members', 'de' => 'Mitglieder', 'es' => 'Miembros', 'zh' => '成员', 'ja' => 'メンバー', 'pl' => 'Członkowie'],
    'home.stat.events'      => ['fr' => 'Événements', 'en' => 'Events', 'de' => 'Veranstaltungen', 'es' => 'Eventos', 'zh' => '活动', 'ja' => 'イベント', 'pl' => 'Wydarzenia'],
    'home.stat.easy'        => ['fr' => 'Prise de tête', 'en' => 'Hassle', 'de' => 'Stress', 'es' => 'Complicaciones', 'zh' => '烦恼', 'ja' => '手間', 'pl' => 'Stres'],
    'home.stats.aria'       => ['fr' => "L'AEIC en chiffres", 'en' => 'The AEIC in numbers', 'de' => 'Die AEIC in Zahlen', 'es' => 'La AEIC en cifras', 'zh' => 'AEIC 数据', 'ja' => 'AEICを数字で', 'pl' => 'AEIC w liczbach'],
    'home.upcoming.eyebrow' => ['fr' => 'Agenda', 'en' => 'Agenda', 'de' => 'Termine', 'es' => 'Agenda', 'zh' => '日程', 'ja' => '予定', 'pl' => 'Agenda'],
    'home.upcoming.title'   => ['fr' => 'Prochains événements', 'en' => 'Upcoming events', 'de' => 'Anstehende Veranstaltungen', 'es' => 'Próximos eventos', 'zh' => '即将到来的活动', 'ja' => '今後のイベント', 'pl' => 'Nadchodzące wydarzenia'],
    'home.upcoming.empty'   => ['fr' => 'Aucun événement annoncé pour le moment. Revenez bientôt !', 'en' => 'No events announced yet. Check back soon!', 'de' => 'Noch keine Veranstaltungen angekündigt. Schau bald wieder vorbei!', 'es' => 'Ningún evento anunciado por ahora. ¡Vuelve pronto!', 'zh' => '暂无公布的活动。敬请期待!', 'ja' => 'まだ告知されたイベントはありません。また来てください!', 'pl' => 'Brak ogłoszonych wydarzeń. Wracaj wkrótce!'],
    'home.upcoming.more'    => ['fr' => 'Tout voir →', 'en' => 'See all →', 'de' => 'Alle ansehen →', 'es' => 'Ver todo →', 'zh' => '查看全部 →', 'ja' => 'すべて見る →', 'pl' => 'Zobacz wszystko →'],

    /* ----------------------------------------------------------------- */
    /*  Événements (liste)                                               */
    /* ----------------------------------------------------------------- */
    'events.eyebrow'        => ['fr' => 'Agenda AEIC', 'en' => 'AEIC agenda', 'de' => 'AEIC-Terminkalender', 'es' => 'Agenda AEIC', 'zh' => 'AEIC 日程', 'ja' => 'AEICアジェンダ', 'pl' => 'Agenda AEIC'],
    'events.title'          => ['fr' => 'Les prochains rendez-vous.', 'en' => 'The next meetups.', 'de' => 'Die nächsten Termine.', 'es' => 'Los próximos encuentros.', 'zh' => '接下来的活动。', 'ja' => '今後の予定。', 'pl' => 'Nadchodzące spotkania.'],
    'events.lead'           => ['fr' => '{a} à venir · {b} passés', 'en' => '{a} upcoming · {b} past', 'de' => '{a} anstehend · {b} vorbei', 'es' => '{a} próximos · {b} pasados', 'zh' => '{a} 即将 · {b} 已结束', 'ja' => '{a} 予定 · {b} 終了', 'pl' => '{a} nadchodzących · {b} minionych'],
    'events.empty'          => ['fr' => 'Aucun événement à venir pour le moment. Revenez vite !', 'en' => 'No upcoming events yet. Check back soon!', 'de' => 'Aktuell keine anstehenden Veranstaltungen. Schau bald wieder vorbei!', 'es' => 'Ningún evento próximo por ahora. ¡Vuelve pronto!', 'zh' => '暂无即将到来的活动。敬请期待!', 'ja' => '今後のイベントはまだありません。また来てください!', 'pl' => 'Brak nadchodzących wydarzeń. Wracaj wkrótce!'],
    'events.archives'       => ['fr' => 'Archives', 'en' => 'Archives', 'de' => 'Archiv', 'es' => 'Archivos', 'zh' => '归档', 'ja' => 'アーカイブ', 'pl' => 'Archiwum'],
    'events.others'         => ['fr' => 'Autres', 'en' => 'Other', 'de' => 'Sonstige', 'es' => 'Otros', 'zh' => '其他', 'ja' => 'その他', 'pl' => 'Inne'],

    /* ----------------------------------------------------------------- */
    /*  Événement (détail)                                               */
    /* ----------------------------------------------------------------- */
    'event.back'            => ['fr' => '← Retour aux événements', 'en' => '← Back to events', 'de' => '← Zurück zu Veranstaltungen', 'es' => '← Volver a eventos', 'zh' => '← 返回活动', 'ja' => '← イベントに戻る', 'pl' => '← Wróć do wydarzeń'],
    'event.eyebrow'         => ['fr' => 'Événement', 'en' => 'Event', 'de' => 'Veranstaltung', 'es' => 'Evento', 'zh' => '活动', 'ja' => 'イベント', 'pl' => 'Wydarzenie'],
    'event.ended'           => ['fr' => 'Événement terminé', 'en' => 'Event ended', 'de' => 'Veranstaltung beendet', 'es' => 'Evento finalizado', 'zh' => '活动已结束', 'ja' => 'イベント終了', 'pl' => 'Wydarzenie zakończone'],
    'event.details'         => ['fr' => 'Détails', 'en' => 'Details', 'de' => 'Details', 'es' => 'Detalles', 'zh' => '详情', 'ja' => '詳細', 'pl' => 'Szczegóły'],
    'event.gallery'         => ['fr' => 'Galerie', 'en' => 'Gallery', 'de' => 'Galerie', 'es' => 'Galería', 'zh' => '图库', 'ja' => 'ギャラリー', 'pl' => 'Galeria'],
    'event.photos'          => ['fr' => 'Photos', 'en' => 'Photos', 'de' => 'Fotos', 'es' => 'Fotos', 'zh' => '照片', 'ja' => '写真', 'pl' => 'Zdjęcia'],
    'event.add_calendar'    => ['fr' => '📅 Ajouter au calendrier', 'en' => '📅 Add to calendar', 'de' => '📅 Zum Kalender hinzufügen', 'es' => '📅 Añadir al calendario', 'zh' => '📅 添加到日历', 'ja' => '📅 カレンダーに追加', 'pl' => '📅 Dodaj do kalendarza'],
    'event.location'        => ['fr' => 'Localisation', 'en' => 'Location', 'de' => 'Standort', 'es' => 'Ubicación', 'zh' => '位置', 'ja' => '場所', 'pl' => 'Lokalizacja'],
    'event.where'           => ['fr' => "Où se trouve l'événement", 'en' => 'Where the event takes place', 'de' => 'Wo die Veranstaltung stattfindet', 'es' => 'Dónde se realiza el evento', 'zh' => '活动地点', 'ja' => 'イベントの場所', 'pl' => 'Gdzie odbywa się wydarzenie'],
    'event.itinerary'       => ['fr' => '📍 Itinéraire (Google Maps)', 'en' => '📍 Directions (Google Maps)', 'de' => '📍 Route (Google Maps)', 'es' => '📍 Cómo llegar (Google Maps)', 'zh' => '📍 路线 (Google 地图)', 'ja' => '📍 道順 (Google マップ)', 'pl' => '📍 Trasa (Google Maps)'],
    'event.participate'     => ['fr' => 'Participer', 'en' => 'Take part', 'de' => 'Teilnehmen', 'es' => 'Participar', 'zh' => '参与', 'ja' => '参加', 'pl' => 'Weź udział'],
    'event.price'           => ['fr' => 'Prix', 'en' => 'Price', 'de' => 'Preis', 'es' => 'Precio', 'zh' => '价格', 'ja' => '料金', 'pl' => 'Cena'],
    'event.free'            => ['fr' => 'Gratuit', 'en' => 'Free', 'de' => 'Kostenlos', 'es' => 'Gratis', 'zh' => '免费', 'ja' => '無料', 'pl' => 'Bezpłatne'],
    'event.places_left'     => ['fr' => 'Plus que {n} place(s)', 'en' => 'Only {n} spot(s) left', 'de' => 'Noch {n} Platz/Plätze', 'es' => '{n} plaza(s) libre(s)', 'zh' => '仅剩 {n} 个名额', 'ja' => '残り {n} 席', 'pl' => 'Zostało {n} miejsc'],
    'event.signed_up'       => ['fr' => '{a}/{b} inscrit·e·s', 'en' => '{a}/{b} registered', 'de' => '{a}/{b} angemeldet', 'es' => '{a}/{b} inscritos', 'zh' => '{a}/{b} 已报名', 'ja' => '{a}/{b} 登録済み', 'pl' => '{a}/{b} zapisanych'],
    'event.full'            => ['fr' => 'Complet', 'en' => 'Full', 'de' => 'Voll', 'es' => 'Completo', 'zh' => '已满', 'ja' => '満員', 'pl' => 'Brak miejsc'],
    'event.registered'      => ['fr' => 'Vous êtes inscrit·e', 'en' => 'You are registered', 'de' => 'Du bist angemeldet', 'es' => 'Estás inscrito', 'zh' => '您已报名', 'ja' => '登録済みです', 'pl' => 'Jesteś zapisany'],
    'event.unregister'      => ['fr' => 'Se désinscrire', 'en' => 'Unregister', 'de' => 'Abmelden', 'es' => 'Cancelar inscripción', 'zh' => '取消报名', 'ja' => '登録を取り消す', 'pl' => 'Wypisz się'],
    'event.waitlist'        => ['fr' => "Sur liste d'attente — position {n}", 'en' => 'On the waitlist — position {n}', 'de' => 'Auf der Warteliste — Position {n}', 'es' => 'En lista de espera — posición {n}', 'zh' => '候补名单 — 第 {n} 位', 'ja' => 'キャンセル待ち — {n} 番目', 'pl' => 'Na liście oczekujących — pozycja {n}'],
    'event.leave_queue'     => ['fr' => 'Quitter la file', 'en' => 'Leave the queue', 'de' => 'Warteschlange verlassen', 'es' => 'Salir de la cola', 'zh' => '退出排队', 'ja' => '待機列を離れる', 'pl' => 'Opuść kolejkę'],
    'event.choose'          => ['fr' => '— Choisir —', 'en' => '— Choose —', 'de' => '— Auswählen —', 'es' => '— Elegir —', 'zh' => '— 选择 —', 'ja' => '— 選択 —', 'pl' => '— Wybierz —'],
    'event.required'        => ['fr' => 'Obligatoire', 'en' => 'Required', 'de' => 'Erforderlich', 'es' => 'Obligatorio', 'zh' => '必选', 'ja' => '必須', 'pl' => 'Wymagane'],
    'event.register_btn'    => ["fr" => "Je m'inscris", 'en' => 'Register', 'de' => 'Anmelden', 'es' => 'Inscribirme', 'zh' => '报名', 'ja' => '登録する', 'pl' => 'Zapisz się'],
    'event.join_waitlist'   => ['fr' => "Liste d'attente", 'en' => 'Join waitlist', 'de' => 'Warteliste', 'es' => 'Lista de espera', 'zh' => '加入候补', 'ja' => 'キャンセル待ち', 'pl' => 'Lista oczekujących'],
    'event.login_to_register' => ['fr' => 'Connectez-vous pour vous inscrire à cet événement.', 'en' => 'Log in to register for this event.', 'de' => 'Melde dich an, um dich für diese Veranstaltung anzumelden.', 'es' => 'Inicia sesión para inscribirte en este evento.', 'zh' => '登录后即可报名此活动。', 'ja' => 'このイベントに登録するにはログインしてください。', 'pl' => 'Zaloguj się, aby zapisać się na to wydarzenie.'],
    'event.login_btn'       => ['fr' => 'Se connecter', 'en' => 'Log in', 'de' => 'Anmelden', 'es' => 'Iniciar sesión', 'zh' => '登录', 'ja' => 'ログイン', 'pl' => 'Zaloguj'],
    'event.create_account'  => ['fr' => 'Créer un compte', 'en' => 'Create account', 'de' => 'Konto erstellen', 'es' => 'Crear cuenta', 'zh' => '创建账户', 'ja' => 'アカウントを作成', 'pl' => 'Utwórz konto'],
    'event.participants'    => ['fr' => 'Participants', 'en' => 'Participants', 'de' => 'Teilnehmer', 'es' => 'Participantes', 'zh' => '参与者', 'ja' => '参加者', 'pl' => 'Uczestnicy'],
    'event.no_participants' => ['fr' => 'Soyez les premiers à vous inscrire !', 'en' => 'Be the first to register!', 'de' => 'Sei der/die Erste!', 'es' => '¡Sé el primero en inscribirte!', 'zh' => '成为第一个报名的人!', 'ja' => '最初の登録者になろう!', 'pl' => 'Bądź pierwszą osobą, która się zapisze!'],
    'event.qr.checkin'      => ['fr' => 'QR code de check-in', 'en' => 'Check-in QR code', 'de' => 'Check-in-QR-Code', 'es' => 'Código QR de check-in', 'zh' => '签到二维码', 'ja' => 'チェックインQRコード', 'pl' => 'Kod QR do odprawy'],
    'event.qr.help'         => ['fr' => "Présentez ce QR code à l'entrée de l'événement.", 'en' => 'Show this QR code at the event entrance.', 'de' => 'Zeige diesen QR-Code am Eingang der Veranstaltung.', 'es' => 'Muestra este código QR en la entrada del evento.', 'zh' => '请在活动入口处出示此二维码。', 'ja' => 'イベントの入り口でこのQRコードを提示してください。', 'pl' => 'Pokaż ten kod QR przy wejściu na wydarzenie.'],
    'event.map.aria'        => ['fr' => 'Carte — {title}', 'en' => 'Map — {title}', 'de' => 'Karte — {title}', 'es' => 'Mapa — {title}', 'zh' => '地图 — {title}', 'ja' => '地図 — {title}', 'pl' => 'Mapa — {title}'],

    /* ----------------------------------------------------------------- */
    /*  Présentation                                                     */
    /* ----------------------------------------------------------------- */
    'about.eyebrow'         => ['fr' => 'Qui sommes-nous ?', 'en' => 'Who are we?', 'de' => 'Wer wir sind', 'es' => 'Quiénes somos', 'zh' => '我们是谁?', 'ja' => '私たちについて', 'pl' => 'Kim jesteśmy?'],
    'about.title'           => ['fr' => "L'AEIC, c'est le campus qui prend vie.", 'en' => 'The AEIC brings the campus to life.', 'de' => 'Die AEIC belebt den Campus.', 'es' => 'La AEIC da vida al campus.', 'zh' => 'AEIC,让校园充满活力。', 'ja' => 'AEICは、命を吹き込まれたキャンパスです。', 'pl' => 'AEIC ożywia kampus.'],
    'about.lead'            => ['fr' => 'Association Étudiante Informatique de Calais — fait par les étudiants, pour les étudiants.', 'en' => 'Student Computer Association of Calais — made by students, for students.', 'de' => 'Studierendenverein Informatik Calais — von Studierenden, für Studierende.', 'es' => 'Asociación Estudiantil de Informática de Calais — hecho por estudiantes, para estudiantes.', 'zh' => '加来计算机学生协会 —— 由学生打造,为学生服务。', 'ja' => 'カレー情報科学学生協会 — 学生による、学生のための運営。', 'pl' => 'Stowarzyszenie Studentów Informatyki w Calais — tworzone przez studentów, dla studentów.'],
    'about.mission'         => ['fr' => 'Notre mission', 'en' => 'Our mission', 'de' => 'Unsere Mission', 'es' => 'Nuestra misión', 'zh' => '我们的使命', 'ja' => '私たちのミッション', 'pl' => 'Nasza misja'],
    'about.mission.desc'    => ['fr' => "Créer du lien entre les étudiants en informatique de Calais, rythmer la vie du campus et rendre concret ce qui ne l'était pas : événements, vie associative, entraide.", 'en' => 'Building connections among CS students in Calais, bringing campus life to a rhythm, and making the abstract concrete: events, student life, mutual aid.', 'de' => 'Verbindungen zwischen den Informatik-Studierenden in Calais schaffen, das Campusleben prägen und das Abstrakte konkret machen: Veranstaltungen, Vereinsleben, gegenseitige Hilfe.', 'es' => 'Crear vínculos entre los estudiantes de informática de Calais, dar ritmo a la vida del campus y hacer concreto lo que no lo era: eventos, vida asociativa, ayuda mutua.', 'zh' => '在加来的计算机学生之间建立联系,为校园生活注入节奏,让抽象变为具体:活动、社团生活、互助。', 'ja' => 'カレーの情報学生の間につながりを作り、キャンパス生活にリズムを与え、抽象的なものを具体化する:イベント、学生団体の活動、助け合い。', 'pl' => 'Tworzyć więzi między studentami informatyki w Calais, nadawać rytm życiu kampusu i czynić konkretne to, co wcześniej nie było: wydarzenia, życie studenckie, wzajemna pomoc.'],
    'about.values.eyebrow'  => ['fr' => 'Nos valeurs', 'en' => 'Our values', 'de' => 'Unsere Werte', 'es' => 'Nuestros valores', 'zh' => '我们的价值观', 'ja' => '私たちの価値観', 'pl' => 'Nasze wartości'],
    'about.values.title'    => ['fr' => 'Ce qui nous fait avancer', 'en' => 'What drives us forward', 'de' => 'Was uns voranbringt', 'es' => 'Lo que nos impulsa', 'zh' => '推动我们前行的力量', 'ja' => '私たちを前へ進めるもの', 'pl' => 'Co nami rusza'],
    'about.value.proximity' => ['fr' => 'Proximité', 'en' => 'Proximity', 'de' => 'Nähe', 'es' => 'Proximidad', 'zh' => '贴近学生', 'ja' => '近さ', 'pl' => 'Bliskość'],
    'about.value.proximity.desc' => ['fr' => 'Des étudiants comme vous, à côté, qui écoutent et agissent.', 'en' => 'Students like you, right next to you, who listen and act.', 'de' => 'Studierende wie du, direkt daneben, die zuhören und handeln.', 'es' => 'Estudiantes como tú, a tu lado, que escuchan y actúan.', 'zh' => '和你一样的学生,就在身边,倾听并行动。', 'ja' => 'あなたと同じ学生が、すぐそばで耳を傾け、行動します。', 'pl' => 'Studenci tacy jak Ty, tuż obok, którzy słuchają i działają.'],
    'about.value.passion'   => ['fr' => 'Passion', 'en' => 'Passion', 'de' => 'Leidenschaft', 'es' => 'Pasión', 'zh' => '热情', 'ja' => '情熱', 'pl' => 'Pasja'],
    'about.value.passion.desc' => ['fr' => "L'informatique et la vie de campus : nos deux moteurs.", 'en' => 'Computer science and campus life: our two driving forces.', 'de' => 'Informatik und Campusleben: unsere zwei Antriebe.', 'es' => 'La informática y la vida del campus: nuestros dos motores.', 'zh' => '计算机与校园生活:我们的两大动力。', 'ja' => '情報科学とキャンパス生活:私たちの二つの原動力。', 'pl' => 'Informatyka i życie kampusu: nasze dwa silniki.'],
    'about.value.sharing'   => ['fr' => 'Partage', 'en' => 'Sharing', 'de' => 'Teilen', 'es' => 'Compartir', 'zh' => '分享', 'ja' => '共有', 'pl' => 'Dzielenie się'],
    'about.value.sharing.desc' => ['fr' => 'Transmettre, entraider, ouvrir des opportunités à tous.', 'en' => 'Passing on knowledge, helping each other, opening opportunities for everyone.', 'de' => 'Wissen weitergeben, einander helfen, allen Chancen eröffnen.', 'es' => 'Transmitir, ayudar, abrir oportunidades a todos.', 'zh' => '传授知识、互助,为每个人打开机会。', 'ja' => '知識を伝え、助け合い、すべての人に機会を開く。', 'pl' => 'Przekazywać wiedzę, pomagać, otwierać możliwości dla wszystkich.'],
    'about.stats.title'     => ['fr' => 'Des actions concrètes', 'en' => 'Concrete actions', 'de' => 'Konkrete Taten', 'es' => 'Acciones concretas', 'zh' => '切实的行动', 'ja' => '具体的な行動', 'pl' => 'Konkretne działania'],
    'about.cta.title'       => ['fr' => 'Envie de nous rejoindre ?', 'en' => 'Want to join us?', 'de' => 'Möchtest du dabei sein?', 'es' => '¿Quieres unirte a nosotros?', 'zh' => '想加入我们吗?', 'ja' => '私たちと一緒に活動しませんか?', 'pl' => 'Chcesz do nas dołączyć?'],

    /* Présentation — contenu structuré (en remplacement du CMS)        */
    'about.vision.title'    => ['fr' => 'Notre vision', 'en' => 'Our vision', 'de' => 'Unsere Vision', 'es' => 'Nuestra visión', 'zh' => '我们的愿景', 'ja' => '私たちのビジョン', 'pl' => 'Nasza wizja'],
    'about.vision.desc'     => ['fr' => "Nous croyons qu'un campus est avant tout une communauté. Notre vision : un lieu où chacun trouve sa place, où les idées prennent forme et où l'informatique rime avec convivialité.", 'en' => 'We believe a campus is, above all, a community. Our vision: a place where everyone fits in, where ideas take shape, and where computer science goes hand in hand with a friendly atmosphere.', 'de' => 'Wir glauben, dass ein Campus vor allem eine Gemeinschaft ist. Unsere Vision: ein Ort, an dem jeder seinen Platz findet, Ideen Gestalt annehmen und Informatik mit Geselligkeit einhergeht.', 'es' => 'Creemos que un campus es, ante todo, una comunidad. Nuestra visión: un lugar donde cada persona encuentra su sitio, donde las ideas toman forma y donde la informática va de la mano con la convivencia.', 'zh' => '我们相信,校园首先是一个社区。我们的愿景:一个让每个人都找到归属的地方,让创意成形,让计算机科学与人情味同行。', 'ja' => 'キャンパスは何よりもコミュニティだと私たちは信じています。私たちのビジョンは、誰もが居場所を見つけ、アイデアが形になり、情報科学と親しみやすさが両立する場所です。', 'pl' => 'Wierzymy, że kampus to przede wszystkim społeczność. Nasza wizja: miejsce, w którym każdy odnajduje swoje miejsce, pomysły nabierają kształtu, a informatyka idzie w parze z życzliwością.'],
    'about.spaces.eyebrow'  => ['fr' => 'Nos espaces', 'en' => 'Our spaces', 'de' => 'Unsere Räume', 'es' => 'Nuestros espacios', 'zh' => '我们的空间', 'ja' => '私たちの空間', 'pl' => 'Nasze przestrzenie'],
    'about.spaces.title'    => ['fr' => 'Des espaces pour tous', 'en' => 'Spaces for everyone', 'de' => 'Räume für alle', 'es' => 'Espacios para todos', 'zh' => '人人可享的空间', 'ja' => 'すべての人のための空間', 'pl' => 'Przestrzenie dla każdego'],
    'about.spaces.desc'     => ['fr' => 'Des lieux pensés pour étudier, échanger et se détendre entre deux cours.', 'en' => 'Places designed to study, chat and unwind between classes.', 'de' => 'Orte zum Lernen, Austauschen und Entspannen zwischen den Vorlesungen.', 'es' => 'Lugares pensados para estudiar, charlar y desconectar entre clases.', 'zh' => '为课间学习、交流和放松而设计的空间。', 'ja' => '授業の合間に勉強したり、語り合ったり、リラックスしたりするために設計された場所。', 'pl' => 'Miejsca stworzone do nauki, rozmów i relaksu między zajęciami.'],
    'about.spaces.free'     => ['fr' => "En accès libre pendant nos horaires d'ouverture : travail en groupe, détente, discussions, tout est prévu.", 'en' => 'Open access during our opening hours: group work, relaxation, chats — everything is covered.', 'de' => 'Während unserer Öffnungszeiten frei zugänglich: Gruppenarbeit, Entspannung, Gespräche — an alles ist gedacht.', 'es' => 'Acceso libre durante nuestro horario de apertura: trabajo en grupo, descanso, charlas, todo está pensado.', 'zh' => '在我们开放时段内自由进出:小组作业、放松、交流,一应俱全。', 'ja' => '開館時間中は自由に利用可能:グループ作業、リラックス、会話、すべて揃っています。', 'pl' => 'Dostęp swobodny w godzinach otwarcia: praca w grupie, relaks, rozmowy — wszystko jest zapewnione.'],
    'about.spaces.local'    => ['fr' => "Dans le local de l'association, retrouvez la cafétéria à prix étudiant, des jeux de société et des membres prêts à donner un coup de main.", 'en' => "In the association's room you'll find the student-priced cafeteria, board games and members ready to help out.", 'de' => 'Im Vereinsraum findest du die Cafeteria zu Studierendenpreisen, Gesellschaftsspiele und Mitglieder, die gerne helfen.', 'es' => 'En el local de la asociación encontrarás la cafetería a precio de estudiante, juegos de mesa y miembros dispuestos a echar una mano.', 'zh' => '在协会活动室,你可以找到学生价的咖啡馆、桌游,以及乐于助人的成员。', 'ja' => '協会の部屋には、学生価格のカフェテリア、ボードゲーム、そして助け合いを惜しまないメンバーがいます。', 'pl' => 'W lokalu stowarzyszenia znajdziesz kafeterię w cenach studenckich, gry planszowe oraz członków gotowych do pomocy.'],
    'about.contact.title'   => ['fr' => 'Coordonnées', 'en' => 'Contact details', 'de' => 'Kontaktangaben', 'es' => 'Datos de contacto', 'zh' => '联系方式', 'ja' => '連絡先', 'pl' => 'Dane kontaktowe'],
    'about.contact.label'   => ['fr' => 'Contact', 'en' => 'Contact', 'de' => 'Kontakt', 'es' => 'Contacto', 'zh' => '联系方式', 'ja' => 'お問い合わせ', 'pl' => 'Kontakt'],
    'about.contact.address' => ['fr' => 'IUT de Calais — département Informatique, 19 Rue Louis David, 62100 Calais', 'en' => 'IUT de Calais — Computer Science department, 19 Rue Louis David, 62100 Calais', 'de' => 'IUT de Calais — Fachbereich Informatik, 19 Rue Louis David, 62100 Calais', 'es' => 'IUT de Calais — departamento de Informática, 19 Rue Louis David, 62100 Calais', 'zh' => '加来 IUT — 计算机系,19 Rue Louis David,62100 Calais', 'ja' => 'カレー IUT — 情報工学科,19 Rue Louis David, 62100 Calais', 'pl' => 'IUT de Calais — wydział Informatyki, 19 Rue Louis David, 62100 Calais'],
    'about.events.eyebrow'  => ['fr' => 'Agenda', 'en' => 'Agenda', 'de' => 'Termine', 'es' => 'Agenda', 'zh' => '日程', 'ja' => '予定', 'pl' => 'Agenda'],
    'about.events.title'    => ['fr' => 'Nos événements phares', 'en' => 'Our flagship events', 'de' => 'Unsere Highlight-Events', 'es' => 'Nuestros eventos estrella', 'zh' => '我们的招牌活动', 'ja' => '私たちの代表的なイベント', 'pl' => 'Nasze flagowe wydarzenia'],
    'about.events.intro'    => ['fr' => "Tout au long de l'année, nous animons le campus avec des moments faits pour se retrouver et souffler.", 'en' => 'All year round, we bring the campus to life with moments designed to bring people together and catch their breath.', 'de' => 'Das ganze Jahr über beleben wir den Campus mit Momenten, die zum Zusammenkommen und Durchatmen einladen.', 'es' => 'A lo largo del año, animamos el campus con momentos pensados para reunitednos y desconectar.', 'zh' => '全年,我们用一个个让彼此相聚、喘口气的时刻,让校园鲜活起来。', 'ja' => '一年を通して、みんなが集まり、ひと息つける瞬間でキャンパスを盛り上げます。', 'pl' => 'Przez cały rok ożywiamy kampus chwilami stworzonymi, by się spotykać i odetchnąć.'],
    'about.events.nuitinfo.title' => ['fr' => 'La Nuit de l\'Info', 'en' => 'Nuit de l\'Info', 'de' => 'Die Nuit de l\'Info', 'es' => 'La Nuit de l\'Info', 'zh' => '信息之夜', 'ja' => 'Nuit de l\'Info(情報の夜)', 'pl' => 'Nuit de l\'Info'],
    'about.events.nuitinfo.desc' => ['fr' => 'Le marathon de programmation national : une nuit pour coder, créer et relever des défis en équipe.', 'en' => 'The national programming marathon: a night to code, create and tackle challenges as a team.', 'de' => 'Der nationale Programmier-Marathon: eine Nacht zum Programmieren, Kreieren und für das Meistern von Herausforderungen im Team.', 'es' => 'El maratón nacional de programación: una noche para programar, crear y superar retos en equipo.', 'zh' => '全国编程马拉松:用一夜的时间,团队一起编码、创造、迎接挑战。', 'ja' => '全国プログラミングマラソン:チームでコードを書き、創り、課題に挑戦する一晩。', 'pl' => 'Krajowy maraton programowania: noc na kodowanie, tworzenie i pokonywanie wyzwań w zespole.'],
    'about.events.afterworks.title' => ['fr' => 'Afterworks', 'en' => 'Afterworks', 'de' => 'Afterworks', 'es' => 'Afterworks', 'zh' => '下班后聚会', 'ja' => 'アフターワーク', 'pl' => 'Afterworks'],
    'about.events.afterworks.desc' => ['fr' => "Des moments conviviaux en fin de journée pour souffler et faire connaissance autour d'un verre.", 'en' => 'Friendly moments at the end of the day to unwind and get to know each other over a drink.', 'de' => 'Gesellige Momente am Tagesende zum Durchatmen und Kennenlernen bei einem Drink.', 'es' => 'Momentos agradables al final del día para desconectar y conocerse alrededor de una bebida.', 'zh' => '在一天结束时,用轻松的时刻放松彼此、喝杯东西互相认识。', 'ja' => '一日の終わりに、ひと息つきながら一杯囲んで親睦を深める和やかな時間。', 'pl' => 'Przyjemne chwile pod koniec dnia, by odetchnąć i lepiej się poznać przy drinku.'],
    'about.events.bbq.title' => ['fr' => 'Barbecues', 'en' => 'Barbecues', 'de' => 'Grillfeste', 'es' => 'Barbacoas', 'zh' => '烧烤', 'ja' => 'バーベキュー', 'pl' => 'Grille'],
    'about.events.bbq.desc' => ['fr' => 'Le rendez-vous gourmand du campus : bonne humeur et partage au menu.', 'en' => 'The campus tastiest get-together: good vibes and sharing on the menu.', 'de' => 'Das leckere Treffen auf dem Campus: gute Laune und Teilen stehen auf dem Programm.', 'es' => 'El encuentro más sabroso del campus: buen ambiente y compartir están en el menú.', 'zh' => '校园里的美味聚会:菜单上写着好心情与分享。', 'ja' => 'キャンパスで一番おいしい集い:メニューは楽しい雰囲気とシェア。', 'pl' => 'Najsmaczniejsze spotkanie na kampusie: w menu dobry nastrój i dzielenie się.'],
    'about.events.bowling.title' => ['fr' => 'Soirées bowling', 'en' => 'Bowling nights', 'de' => 'Bowling-Abende', 'es' => 'Noches de bolos', 'zh' => '保龄球之夜', 'ja' => 'ボウリングの夕べ', 'pl' => 'Wieczory kręgli'],
    'about.events.bowling.desc' => ['fr' => 'Des soirées ludiques pour se défier entre amis et changer d\'air.', 'en' => 'Fun nights to challenge each other among friends and get a change of scenery.', 'de' => 'Spielerische Abende, um sich unter Freunden zu messen und auf andere Gedanken zu kommen.', 'es' => 'Noches lúdicas para desafiar a tus amigos y cambiar de aires.', 'zh' => '充满乐趣的夜晚,在朋友间相互挑战、换换心情。', 'ja' => '友達と競い合い、気分転換できる楽しい夜。', 'pl' => 'Zabawne wieczory, by rywalizować z przyjaciółmi i zmienić otoczenie.'],
    'about.events.bar.title' => ['fr' => 'Sorties bar', 'en' => 'Bar outings', 'de' => 'Bar-Touren', 'es' => 'Salidas de bar', 'zh' => '酒吧小聚', 'ja' => 'バーへの外出', 'pl' => 'Wyjścia na bar'],
    'about.events.bar.desc' => ['fr' => "Pour finir la journée ensemble, dans une ambiance détendue et friendly.", 'en' => 'To end the day together, in a relaxed and friendly atmosphere.', 'de' => 'Um den Tag gemeinsam ausklingen zu lassen, in entspannter und freundlicher Atmosphäre.', 'es' => 'Para terminar el día juntos, en un ambiente relajado y amistoso.', 'zh' => '在轻松友好的氛围中,一起结束这一天。', 'ja' => 'リラックスしてフレンドリーな雰囲気のなか、一日を一緒に締めくくる。', 'pl' => 'By zakończyć dzień razem, w swobodnej i przyjaznej atmosferze.'],
    'about.events.closing'  => ['fr' => "Et ce n'est qu'un aperçu : d'autres événements voient le jour chaque saison, selon vos envies.", 'en' => "And that's just a glimpse: more events come to life every season, based on what you want.", 'de' => 'Und das ist nur ein Vorgeschmack: jede Saison entstehen weitere Veranstaltungen, ganz nach euren Wünschen.', 'es' => 'Y esto es solo un anticipo: cada temporada surgen nuevos eventos, según lo que os apetezca.', 'zh' => '这只是一个缩影:每个季节都会有新的活动诞生,随你的期待而变化。', 'ja' => 'これはほんの一部。みなさんの声に応じて、毎シーズン新しいイベントが生まれます。', 'pl' => 'To tylko zarys: co sezon powstają kolejne wydarzenia, zgodnie z Waszymi oczekiwaniami.'],

    /* ----------------------------------------------------------------- */
    /*  Carte (section « Où nous trouver »)                              */
    /* ----------------------------------------------------------------- */
    'map.eyebrow'           => ['fr' => 'Nous localiser', 'en' => 'Find us', 'de' => 'Uns finden', 'es' => 'Encuéntranos', 'zh' => '找到我们', 'ja' => 'アクセス', 'pl' => 'Znajdź nas'],
    'map.title'             => ['fr' => 'Où nous trouver', 'en' => 'Where to find us', 'de' => 'Wo du uns findest', 'es' => 'Dónde encontrarnos', 'zh' => '在哪里找到我们', 'ja' => '私たちの場所', 'pl' => 'Gdzie nas znaleźć'],
    'map.card_title'        => ['fr' => 'IUT de Calais — Informatique', 'en' => 'IUT de Calais — Computer Science', 'de' => 'IUT de Calais — Informatik', 'es' => 'IUT de Calais — Informática', 'zh' => '加来 IUT — 计算机', 'ja' => 'カレー IUT — 情報工学', 'pl' => 'IUT de Calais — Informatyka'],
    'map.address'           => ['fr' => '19 Rue Louis David, 62100 Calais', 'en' => '19 Rue Louis David, 62100 Calais', 'de' => '19 Rue Louis David, 62100 Calais', 'es' => '19 Rue Louis David, 62100 Calais', 'zh' => '19 Rue Louis David, 62100 Calais', 'ja' => '19 Rue Louis David, 62100 Calais', 'pl' => '19 Rue Louis David, 62100 Calais'],
    'map.directions'        => ['fr' => '📍 Itinéraire (Google Maps)', 'en' => '📍 Directions (Google Maps)', 'de' => '📍 Route (Google Maps)', 'es' => '📍 Cómo llegar (Google Maps)', 'zh' => '📍 路线 (Google 地图)', 'ja' => '📍 道順 (Google マップ)', 'pl' => '📍 Trasa (Google Maps)'],
    'map.osm'               => ['fr' => 'Voir sur OpenStreetMap', 'en' => 'View on OpenStreetMap', 'de' => 'Auf OpenStreetMap ansehen', 'es' => 'Ver en OpenStreetMap', 'zh' => '在 OpenStreetMap 上查看', 'ja' => 'OpenStreetMapで見る', 'pl' => 'Zobacz na OpenStreetMap'],
    'map.expand'            => ['fr' => 'Agrandir la carte', 'en' => 'Expand the map', 'de' => 'Karte vergrößern', 'es' => 'Ampliar el mapa', 'zh' => '放大地图', 'ja' => '地図を拡大', 'pl' => 'Powiększ mapę'],
    'map.shrink'            => ['fr' => 'Réduire la carte', 'en' => 'Shrink the map', 'de' => 'Karte verkleinern', 'es' => 'Reducir el mapa', 'zh' => '缩小地图', 'ja' => '地図を縮小', 'pl' => 'Pomniejsz mapę'],
    'map.iframe.title'      => ['fr' => 'Carte interactive — IUT de Calais', 'en' => 'Interactive map — IUT de Calais', 'de' => 'Interaktive Karte — IUT de Calais', 'es' => 'Mapa interactivo — IUT de Calais', 'zh' => '互动地图 — 加来 IUT', 'ja' => 'インタラクティブマップ — カレー IUT', 'pl' => 'Mapa interaktywna — IUT de Calais'],

    /* ----------------------------------------------------------------- */
    /*  Équipe                                                           */
    /* ----------------------------------------------------------------- */
    'team.eyebrow'          => ['fr' => 'Le bureau', 'en' => 'The board', 'de' => 'Der Vorstand', 'es' => 'La junta', 'zh' => '核心团队', 'ja' => '役員', 'pl' => 'Zarząd'],
    'team.title'            => ['fr' => "Ceux qui font vivre l'AEIC.", 'en' => 'The people behind the AEIC.', 'de' => 'Die, die die AEIC am Leben erhalten.', 'es' => 'Quienes mantienen viva la AEIC.', 'zh' => '让 AEIC 充满活力的人。', 'ja' => 'AEICを支える人々。', 'pl' => 'Osoby, które ożywiają AEIC.'],
    'team.lead'             => ['fr' => 'Les étudiants du bureau, pôle par pôle.', 'en' => 'The board students, area by area.', 'de' => 'Die Studierenden des Vorstands, Bereich für Bereich.', 'es' => 'Los estudiantes de la junta, área por área.', 'zh' => '核心团队的学生,按部门介绍。', 'ja' => '役員の学生を、部門ごとに。', 'pl' => 'Studenci zarządu, pion po pionie.'],
    'team.empty'            => ['fr' => 'Contenu à venir. Le bureau sera bientôt présenté ici.', 'en' => 'Content coming soon. The board will be presented here shortly.', 'de' => 'Inhalt folgt. Der Vorstand wird hier bald vorgestellt.', 'es' => 'Contenido próximamente. La junta se presentará aquí pronto.', 'zh' => '内容即将上线,核心团队将很快在此展示。', 'ja' => 'コンテンツ準備中。役員はまもなくここで紹介されます。', 'pl' => 'Treść wkrótce. Zarząd zostanie tu wkrótce zaprezentowany.'],
    'team.board.eyebrow'    => ['fr' => 'Bureau restreint', 'en' => 'Core board', 'de' => 'Kernvorstand', 'es' => 'Junta principal', 'zh' => '核心管理层', 'ja' => '役員コア', 'pl' => 'Zarząd główny'],
    'team.board.title'      => ['fr' => 'Le bureau', 'en' => 'The board', 'de' => 'Der Vorstand', 'es' => 'La junta', 'zh' => '管理层', 'ja' => '役員', 'pl' => 'Zarząd'],
    'team.all.eyebrow'      => ['fr' => "Toute l'équipe", 'en' => 'The whole team', 'de' => 'Das gesamte Team', 'es' => 'Todo el equipo', 'zh' => '全部成员', 'ja' => 'チーム全体', 'pl' => 'Cały zespół'],
    'team.all.title'        => ['fr' => 'Les membres', 'en' => 'The members', 'de' => 'Die Mitglieder', 'es' => 'Los miembros', 'zh' => '成员', 'ja' => 'メンバー', 'pl' => 'Członkowie'],

    /* ----------------------------------------------------------------- */
    /*  Sondages (liste + détail)                                        */
    /* ----------------------------------------------------------------- */
    'polls.eyebrow'         => ['fr' => 'Sondages AEIC', 'en' => 'AEIC polls', 'de' => 'AEIC-Umfragen', 'es' => 'Encuestas AEIC', 'zh' => 'AEIC 投票', 'ja' => 'AEICアンケート', 'pl' => 'Ankiety AEIC'],
    'polls.title'           => ['fr' => 'Votre avis compte.', 'en' => 'Your opinion matters.', 'de' => 'Deine Meinung zählt.', 'es' => 'Tu opinión cuenta.', 'zh' => '你的意见很重要。', 'ja' => 'あなたの声は大事です。', 'pl' => 'Twoja opinia się liczy.'],
    'polls.lead'            => ['fr' => '{n} sondage(s) · résultats en temps réel', 'en' => '{n} poll(s) · real-time results', 'de' => '{n} Umfrage(n) · Ergebnisse in Echtzeit', 'es' => '{n} encuesta(s) · resultados en tiempo real', 'zh' => '{n} 个投票 · 实时结果', 'ja' => '{n} 件のアンケート · リアルタイム結果', 'pl' => '{n} ankieta · wyniki na żywo'],
    'polls.empty'           => ['fr' => 'Aucun sondage ouvert pour le moment. Revenez vite !', 'en' => 'No open polls yet. Check back soon!', 'de' => 'Aktuell keine offenen Umfragen. Schau bald wieder vorbei!', 'es' => 'Ninguna encuesta abierta por ahora. ¡Vuelve pronto!', 'zh' => '暂无开放的投票。敬请期待!', 'ja' => '現在開いているアンケートはありません。また来てください!', 'pl' => 'Brak otwartych ankiet. Wracaj wkrótce!'],
    'poll.back'             => ['fr' => '← Retour aux sondages', 'en' => '← Back to polls', 'de' => '← Zurück zu den Umfragen', 'es' => '← Volver a las encuestas', 'zh' => '← 返回投票', 'ja' => '← アンケートに戻る', 'pl' => '← Wróć do ankiet'],
    'poll.eyebrow.lg'       => ['fr' => '📊 Sondage', 'en' => '📊 Poll', 'de' => '📊 Umfrage', 'es' => '📊 Encuesta', 'zh' => '📊 投票', 'ja' => '📊 アンケート', 'pl' => '📊 Ankieta'],
    'poll.closed'           => ['fr' => '🔒 Fermé', 'en' => '🔒 Closed', 'de' => '🔒 Geschlossen', 'es' => '🔒 Cerrada', 'zh' => '🔒 已关闭', 'ja' => '🔒 終了', 'pl' => '🔒 Zamknięta'],
    'poll.open'             => ['fr' => '🟢 Ouvert', 'en' => '🟢 Open', 'de' => '🟢 Offen', 'es' => '🟢 Abierta', 'zh' => '🟢 开放中', 'ja' => '🟢 受付中', 'pl' => '🟢 Otwarta'],
    'poll.in_progress'      => ['fr' => '📊 En cours', 'en' => '📊 In progress', 'de' => '📊 Läuft', 'es' => '📊 En curso', 'zh' => '📊 进行中', 'ja' => '📊 進行中', 'pl' => '📊 W toku'],
    'poll.multiple'         => ['fr' => '☑️ Choix multiple', 'en' => '☑️ Multiple choice', 'de' => '☑️ Mehrfachauswahl', 'es' => '☑️ Elección múltiple', 'zh' => '☑️ 多选', 'ja' => '☑️ 複数選択', 'pl' => '☑️ Wielokrotnego wyboru'],
    'poll.single'           => ['fr' => '🔘 Choix unique', 'en' => '🔘 Single choice', 'de' => '🔘 Einfachauswahl', 'es' => '🔘 Elección única', 'zh' => '🔘 单选', 'ja' => '🔘 単一選択', 'pl' => '🔘 Pojedynczego wyboru'],
    'poll.voters'           => ['fr' => '👥 {n} votant(s)', 'en' => '👥 {n} voter(s)', 'de' => '👥 {n} Stimmberechtigte', 'es' => '👥 {n} votante(s)', 'zh' => '👥 {n} 位投票者', 'ja' => '👥 {n} 人の投票者', 'pl' => '👥 {n} głosujących'],
    'poll.vote.eyebrow'     => ['fr' => 'Votre avis compte', 'en' => 'Your opinion matters', 'de' => 'Deine Meinung zählt', 'es' => 'Tu opinión cuenta', 'zh' => '你的意见很重要', 'ja' => 'あなたの声は大事です', 'pl' => 'Twoja opinia się liczy'],
    'poll.vote.now'         => ['fr' => 'Votez maintenant', 'en' => 'Vote now', 'de' => 'Jetzt abstimmen', 'es' => 'Vota ahora', 'zh' => '立即投票', 'ja' => '今すぐ投票', 'pl' => 'Głosuj teraz'],
    'poll.vote.multiple.desc' => ['fr' => 'Vous pouvez choisir plusieurs réponses.', 'en' => 'You can choose several answers.', 'de' => 'Du kannst mehrere Antworten wählen.', 'es' => 'Puedes elegir varias respuestas.', 'zh' => '你可以选择多个选项。', 'ja' => '複数の回答を選択できます。', 'pl' => 'Możesz wybrać kilka odpowiedzi.'],
    'poll.vote.single.desc' => ['fr' => 'Choisissez une seule réponse.', 'en' => 'Choose a single answer.', 'de' => 'Wähle nur eine Antwort.', 'es' => 'Elige una sola respuesta.', 'zh' => '请选择一个选项。', 'ja' => '回答を一つ選んでください。', 'pl' => 'Wybierz jedną odpowiedź.'],
    'poll.vote.submit'      => ['fr' => '🗳️ Voter', 'en' => '🗳️ Vote', 'de' => '🗳️ Abstimmen', 'es' => '🗳️ Votar', 'zh' => '🗳️ 投票', 'ja' => '🗳️ 投票する', 'pl' => '🗳️ Głosuj'],
    'poll.results'          => ['fr' => 'Résultats', 'en' => 'Results', 'de' => 'Ergebnisse', 'es' => 'Resultados', 'zh' => '结果', 'ja' => '結果', 'pl' => 'Wyniki'],
    'poll.results.live'     => ['fr' => '📊 Résultats en direct', 'en' => '📊 Live results', 'de' => '📊 Live-Ergebnisse', 'es' => '📊 Resultados en directo', 'zh' => '📊 实时结果', 'ja' => '📊 リアルタイム結果', 'pl' => '📊 Wyniki na żywo'],
    'poll.thanks'           => ['fr' => '✅ Merci pour votre vote !', 'en' => '✅ Thanks for your vote!', 'de' => '✅ Danke für deine Stimme!', 'es' => '✅ ¡Gracias por tu voto!', 'zh' => '✅ 感谢你的投票!', 'ja' => '✅ 投票ありがとうございます!', 'pl' => '✅ Dziękujemy za głos!'],
    'poll.closed.label'     => ['fr' => '🔒 Sondage terminé', 'en' => '🔒 Poll closed', 'de' => '🔒 Umfrage beendet', 'es' => '🔒 Encuesta cerrada', 'zh' => '🔒 投票已结束', 'ja' => '🔒 アンケート終了', 'pl' => '🔒 Ankieta zakończona'],
    'poll.no_votes'         => ['fr' => 'Aucun vote pour le moment. Soyez le premier !', 'en' => 'No votes yet. Be the first!', 'de' => 'Noch keine Stimmen abgegeben. Sei der/die Erste!', 'es' => 'Aún no hay votos. ¡Sé el primero!', 'zh' => '暂无投票。成为第一个!', 'ja' => 'まだ投票はありません。最初の人になろう!', 'pl' => 'Brak głosów. Bądź pierwszy!'],
    'poll.your_vote'        => ['fr' => '✓ votre choix', 'en' => '✓ your choice', 'de' => '✓ deine Wahl', 'es' => '✓ tu elección', 'zh' => '✓ 你的选择', 'ja' => '✓ あなたの選択', 'pl' => '✓ twój wybór'],
    'poll.vote.count'       => ['fr' => '{n} vote(s)', 'en' => '{n} vote(s)', 'de' => '{n} Stimme(n)', 'es' => '{n} voto(s)', 'zh' => '{n} 票', 'ja' => '{n} 票', 'pl' => '{n} głos(ów)'],
    'poll.about'            => ['fr' => 'À propos', 'en' => 'About', 'de' => 'Über', 'es' => 'Acerca de', 'zh' => '关于', 'ja' => '概要', 'pl' => 'O programie'],
    'poll.info'             => ['fr' => 'Informations', 'en' => 'Information', 'de' => 'Informationen', 'es' => 'Información', 'zh' => '信息', 'ja' => '情報', 'pl' => 'Informacje'],
    'poll.info.status'      => ['fr' => 'Statut', 'en' => 'Status', 'de' => 'Status', 'es' => 'Estado', 'zh' => '状态', 'ja' => '状態', 'pl' => 'Status'],
    'poll.info.type'        => ['fr' => 'Type', 'en' => 'Type', 'de' => 'Typ', 'es' => 'Tipo', 'zh' => '类型', 'ja' => '種類', 'pl' => 'Typ'],
    'poll.info.voters'      => ['fr' => 'Votants', 'en' => 'Voters', 'de' => 'Abstimmende', 'es' => 'Votantes', 'zh' => '投票者', 'ja' => '投票者', 'pl' => 'Głosujący'],
    'poll.info.options'     => ['fr' => 'Options', 'en' => 'Options', 'de' => 'Optionen', 'es' => 'Opciones', 'zh' => '选项', 'ja' => '選択肢', 'pl' => 'Opcje'],
    'poll.info.closes'      => ['fr' => 'Clôture', 'en' => 'Closes', 'de' => 'Schließt', 'es' => 'Cierre', 'zh' => '截止', 'ja' => '締切', 'pl' => 'Zamknięcie'],
    'poll.login.title'      => ['fr' => 'Connectez-vous pour voter', 'en' => 'Log in to vote', 'de' => 'Anmelden zum Abstimmen', 'es' => 'Inicia sesión para votar', 'zh' => '登录后投票', 'ja' => '投票するにはログイン', 'pl' => 'Zaloguj się, aby głosować'],
    'poll.login.desc'       => ['fr' => "Ce sondage est ouvert aux membres de l'AEIC. Créez un compte ou connectez-vous pour participer et voir les résultats.", 'en' => 'This poll is open to AEIC members. Create an account or log in to take part and see the results.', 'de' => 'Diese Umfrage ist für AEIC-Mitglieder offen. Erstelle ein Konto oder melde dich an, um teilzunehmen und die Ergebnisse zu sehen.', 'es' => 'Esta encuesta está abierta a los miembros de la AEIC. Crea una cuenta o inicia sesión para participar y ver los resultados.', 'zh' => '此投票面向 AEIC 成员开放。创建账户或登录即可参与并查看结果。', 'ja' => 'このアンケートはAEICメンバー向けです。アカウントを作成するかログインして参加し、結果をご覧ください。', 'pl' => 'Ta ankieta jest otwarta dla członków AEIC. Utwórz konto lub zaloguj się, aby wziąć udział i zobaczyć wyniki.'],
    'poll.login.button'     => ['fr' => 'Se connecter', 'en' => 'Log in', 'de' => 'Anmelden', 'es' => 'Iniciar sesión', 'zh' => '登录', 'ja' => 'ログイン', 'pl' => 'Zaloguj'],
    'poll.login.register'   => ['fr' => 'Créer un compte', 'en' => 'Create account', 'de' => 'Konto erstellen', 'es' => 'Crear cuenta', 'zh' => '创建账户', 'ja' => 'アカウントを作成', 'pl' => 'Utwórz konto'],
    'poll.card.multi'       => ['fr' => '☑️ Multi', 'en' => '☑️ Multi', 'de' => '☑️ Multi', 'es' => '☑️ Múltiple', 'zh' => '☑️ 多选', 'ja' => '☑️ 複数', 'pl' => '☑️ Wiele'],
    'poll.card.single'      => ['fr' => '🔘 Unique', 'en' => '🔘 Single', 'de' => '🔘 Einzeln', 'es' => '🔘 Único', 'zh' => '🔘 单选', 'ja' => '🔘 単一', 'pl' => '🔘 Pojedyncze'],
    'poll.card.options'     => ['fr' => '{n} options', 'en' => '{n} options', 'de' => '{n} Optionen', 'es' => '{n} opciones', 'zh' => '{n} 个选项', 'ja' => '{n} つの選択肢', 'pl' => '{n} opcji'],
    'poll.card.view'        => ['fr' => 'Voir →', 'en' => 'View →', 'de' => 'Ansehen →', 'es' => 'Ver →', 'zh' => '查看 →', 'ja' => '見る →', 'pl' => 'Zobacz →'],
    'poll.card.join'        => ['fr' => 'Participer →', 'en' => 'Take part →', 'de' => 'Teilnehmen →', 'es' => 'Participar →', 'zh' => '参与 →', 'ja' => '参加する →', 'pl' => 'Weź udział →'],

    /* ----------------------------------------------------------------- */
    /*  Galerie                                                          */
    /* ----------------------------------------------------------------- */
    'gallery.eyebrow'       => ['fr' => '📷 Galerie', 'en' => '📷 Gallery', 'de' => '📷 Galerie', 'es' => '📷 Galería', 'zh' => '📷 图库', 'ja' => '📷 ギャラリー', 'pl' => '📷 Galeria'],
    'gallery.title'         => ['fr' => 'Photos des événements', 'en' => 'Event photos', 'de' => 'Veranstaltungsfotos', 'es' => 'Fotos de eventos', 'zh' => '活动照片', 'ja' => 'イベントの写真', 'pl' => 'Zdjęcia z wydarzeń'],
    'gallery.lead'          => ['fr' => "Retrouvez en images les meilleurs moments des événements passés de l'AEIC.", 'en' => 'Relive the best moments of past AEIC events in pictures.', 'de' => 'Erlebe die schönsten Momente vergangener AEIC-Veranstaltungen in Bildern.', 'es' => 'Revive en imágenes los mejores momentos de los eventos pasados de la AEIC.', 'zh' => '用图片回顾 AEIC 过往活动的精彩瞬间。', 'ja' => 'AEICの過去のイベントの最高の瞬間を写真でお楽しみください。', 'pl' => 'Ożywj najlepsze chwile minionych wydarzeń AEIC na zdjęciach.'],
    'gallery.empty'         => ['fr' => 'Aucune photo pour le moment. Revenez bientôt après nos prochains événements !', 'en' => 'No photos yet. Check back after our next events!', 'de' => 'Noch keine Fotos. Schau nach unseren nächsten Veranstaltungen wieder vorbei!', 'es' => 'Ninguna foto por ahora. ¡Vuelve después de nuestros próximos eventos!', 'zh' => '暂无照片。下次活动后敬请回来看!', 'ja' => '写真はまだありません。次のイベントの後にまた来てください!', 'pl' => 'Brak zdjęć. Wracaj po naszych kolejnych wydarzeniach!'],
    'gallery.zoom'          => ['fr' => 'Agrandir', 'en' => 'Zoom', 'de' => 'Vergrößern', 'es' => 'Ampliar', 'zh' => '放大', 'ja' => '拡大', 'pl' => 'Powiększ'],
    'gallery.close'         => ['fr' => 'Fermer', 'en' => 'Close', 'de' => 'Schließen', 'es' => 'Cerrar', 'zh' => '关闭', 'ja' => '閉じる', 'pl' => 'Zamknij'],

    /* ----------------------------------------------------------------- */
    /*  Authentification                                                 */
    /* ----------------------------------------------------------------- */
    'auth.login.eyebrow'    => ['fr' => 'Espace membre', 'en' => 'Member area', 'de' => 'Mitgliederbereich', 'es' => 'Zona de miembro', 'zh' => '会员专区', 'ja' => 'メンバーエリア', 'pl' => 'Strefa członka'],
    'auth.login.title'      => ['fr' => 'Connexion', 'en' => 'Log in', 'de' => 'Anmelden', 'es' => 'Iniciar sesión', 'zh' => '登录', 'ja' => 'ログイン', 'pl' => 'Logowanie'],
    'auth.login.email'      => ['fr' => 'Adresse e-mail', 'en' => 'Email address', 'de' => 'E-Mail-Adresse', 'es' => 'Correo electrónico', 'zh' => '电子邮箱', 'ja' => 'メールアドレス', 'pl' => 'Adres e-mail'],
    'auth.login.password'   => ['fr' => 'Mot de passe', 'en' => 'Password', 'de' => 'Passwort', 'es' => 'Contraseña', 'zh' => '密码', 'ja' => 'パスワード', 'pl' => 'Hasło'],
    'auth.login.forgot'     => ['fr' => 'Mot de passe oublié ?', 'en' => 'Forgot password?', 'de' => 'Passwort vergessen?', 'es' => '¿Olvidaste tu contraseña?', 'zh' => '忘记密码?', 'ja' => 'パスワードをお忘れですか?', 'pl' => 'Nie pamiętasz hasła?'],
    'auth.login.submit'     => ['fr' => 'Se connecter', 'en' => 'Log in', 'de' => 'Anmelden', 'es' => 'Iniciar sesión', 'zh' => '登录', 'ja' => 'ログイン', 'pl' => 'Zaloguj'],
    'auth.login.alt'        => ['fr' => 'Pas encore de compte ?', 'en' => 'No account yet?', 'de' => 'Noch kein Konto?', 'es' => '¿Aún no tienes cuenta?', 'zh' => '还没有账户?', 'ja' => 'まだアカウントをお持ちでないですか?', 'pl' => 'Nie masz jeszcze konta?'],
    'auth.register.eyebrow' => ['fr' => "Rejoins l'AEIC", 'en' => 'Join AEIC', 'de' => 'AEIC beitreten', 'es' => 'Únete a la AEIC', 'zh' => '加入 AEIC', 'ja' => 'AEICに参加', 'pl' => 'Dołącz do AEIC'],
    'auth.register.title'   => ['fr' => 'Créer un compte', 'en' => 'Create an account', 'de' => 'Konto erstellen', 'es' => 'Crear una cuenta', 'zh' => '创建账户', 'ja' => 'アカウントを作成', 'pl' => 'Utwórz konto'],
    'auth.register.firstname' => ['fr' => 'Prénom', 'en' => 'First name', 'de' => 'Vorname', 'es' => 'Nombre', 'zh' => '名字', 'ja' => '名', 'pl' => 'Imię'],
    'auth.register.lastname' => ['fr' => 'Nom', 'en' => 'Last name', 'de' => 'Nachname', 'es' => 'Apellidos', 'zh' => '姓氏', 'ja' => '姓', 'pl' => 'Nazwisko'],
    'auth.register.email.hint' => ['fr' => 'Votre mot de passe temporaire vous sera envoyé par e-mail.', 'en' => 'Your temporary password will be sent by email.', 'de' => 'Dein temporäres Passwort wird per E-Mail gesendet.', 'es' => 'Tu contraseña temporal se enviará por correo electrónico.', 'zh' => '临时密码将通过邮件发送给你。', 'ja' => '仮パスワードがメールで送信されます。', 'pl' => 'Twoje hasło tymczasowe zostanie wysłane e-mailem.'],
    'auth.register.consent' => ['fr' => "J'accepte les {cgu} et la {privacy}.", 'en' => 'I accept the {cgu} and the {privacy}.', 'de' => 'Ich akzeptiere die {cgu} und die {privacy}.', 'es' => 'Acepto los {cgu} y la {privacy}.', 'zh' => '我接受{cgu}和{privacy}。', 'ja' => '{cgu}と{privacy}に同意します。', 'pl' => 'Akceptuję {cgu} oraz {privacy}.'],
    'auth.register.cgu'     => ['fr' => "conditions d'utilisation", 'en' => 'terms of use', 'de' => 'Nutzungsbedingungen', 'es' => 'términos de uso', 'zh' => '使用条款', 'ja' => '利用規約', 'pl' => 'regulamin'],
    'auth.register.consent.privacy' => ['fr' => 'politique de confidentialité', 'en' => 'privacy policy', 'de' => 'Datenschutzrichtlinie', 'es' => 'política de privacidad', 'zh' => '隐私政策', 'ja' => 'プライバシーポリシー', 'pl' => 'politykę prywatności'],
    'auth.register.submit'  => ['fr' => 'Créer mon compte', 'en' => 'Create my account', 'de' => 'Konto erstellen', 'es' => 'Crear mi cuenta', 'zh' => '创建我的账户', 'ja' => 'アカウントを作成', 'pl' => 'Utwórz moje konto'],
    'auth.register.alt'     => ['fr' => 'Déjà inscrit ?', 'en' => 'Already registered?', 'de' => 'Bereits registriert?', 'es' => '¿Ya registrado?', 'zh' => '已经注册?', 'ja' => 'すでに登録済みですか?', 'pl' => 'Już zarejestrowany?'],

    /* ----------------------------------------------------------------- */
    /*  Commun                                                           */
    /* ----------------------------------------------------------------- */
    'common.search'         => ['fr' => 'Rechercher', 'en' => 'Search', 'de' => 'Suchen', 'es' => 'Buscar', 'zh' => '搜索', 'ja' => '検索', 'pl' => 'Szukaj'],
    'common.cancel'         => ['fr' => 'Annuler', 'en' => 'Cancel', 'de' => 'Abbrechen', 'es' => 'Cancelar', 'zh' => '取消', 'ja' => 'キャンセル', 'pl' => 'Anuluj'],
    'common.confirm'        => ['fr' => 'Confirmer', 'en' => 'Confirm', 'de' => 'Bestätigen', 'es' => 'Confirmar', 'zh' => '确认', 'ja' => '確認', 'pl' => 'Potwierdź'],
    'common.delete'         => ['fr' => 'Supprimer', 'en' => 'Delete', 'de' => 'Löschen', 'es' => 'Eliminar', 'zh' => '删除', 'ja' => '削除', 'pl' => 'Usuń'],
    'common.save'           => ['fr' => 'Enregistrer', 'en' => 'Save', 'de' => 'Speichern', 'es' => 'Guardar', 'zh' => '保存', 'ja' => '保存', 'pl' => 'Zapisz'],
    'common.back'           => ['fr' => 'Retour', 'en' => 'Back', 'de' => 'Zurück', 'es' => 'Volver', 'zh' => '返回', 'ja' => '戻る', 'pl' => 'Wstecz'],
    'common.see_more'       => ['fr' => 'Voir plus', 'en' => 'See more', 'de' => 'Mehr anzeigen', 'es' => 'Ver más', 'zh' => '查看更多', 'ja' => 'もっと見る', 'pl' => 'Zobacz więcej'],
    'common.download'       => ['fr' => 'Télécharger', 'en' => 'Download', 'de' => 'Herunterladen', 'es' => 'Descargar', 'zh' => '下载', 'ja' => 'ダウンロード', 'pl' => 'Pobierz'],
    'common.details'        => ['fr' => 'Détails', 'en' => 'Details', 'de' => 'Details', 'es' => 'Detalles', 'zh' => '详情', 'ja' => '詳細', 'pl' => 'Szczegóły'],
    'common.featured'       => ['fr' => 'À la une', 'en' => 'Featured', 'de' => 'Im Fokus', 'es' => 'Destacado', 'zh' => '精选', 'ja' => '注目', 'pl' => 'Wyróżnione'],
    'common.optional'       => ['fr' => 'Facultatif', 'en' => 'Optional', 'de' => 'Optional', 'es' => 'Opcional', 'zh' => '可选', 'ja' => '任意', 'pl' => 'Opcjonalne'],
    'common.email'          => ['fr' => 'Adresse e-mail', 'en' => 'Email address', 'de' => 'E-Mail-Adresse', 'es' => 'Correo electrónico', 'zh' => '电子邮箱', 'ja' => 'メールアドレス', 'pl' => 'Adres e-mail'],

    /* ----------------------------------------------------------------- */
    /*  Espace membre / données (RGPD)                                   */
    /* ----------------------------------------------------------------- */
    'account.eyebrow.rgpd'  => ['fr' => 'RGPD · Vos droits', 'en' => 'GDPR · Your rights', 'de' => 'DSGVO · Ihre Rechte', 'es' => 'RGPD · Tus derechos', 'zh' => 'GDPR · 您的权利', 'ja' => 'GDPR · あなたの権利', 'pl' => 'RODO · Twoje prawa'],
    'account.privacy.title' => ['fr' => 'Mes données', 'en' => 'My data', 'de' => 'Meine Daten', 'es' => 'Mis datos', 'zh' => '我的数据', 'ja' => 'マイデータ', 'pl' => 'Moje dane'],
    'account.privacy.lead'  => ['fr' => 'Gérez votre mot de passe, exportez ou supprimez vos données.', 'en' => 'Manage your password, export or delete your data.', 'de' => 'Verwalte dein Passwort, exportiere oder lösche deine Daten.', 'es' => 'Gestiona tu contraseña, exporta o elimina tus datos.', 'zh' => '管理您的密码、导出或删除您的数据。', 'ja' => 'パスワードの管理、データのエクスポート・削除が行えます。', 'pl' => 'Zarządzaj hasłem, eksportuj lub usuń swoje dane.'],
    'account.password.title' => ['fr' => 'Changer mon mot de passe', 'en' => 'Change my password', 'de' => 'Mein Passwort ändern', 'es' => 'Cambiar mi contraseña', 'zh' => '修改我的密码', 'ja' => 'パスワードを変更', 'pl' => 'Zmień moje hasło'],
    'account.password.sub'  => ['fr' => 'Un email de confirmation vous sera envoyé.', 'en' => 'A confirmation email will be sent to you.', 'de' => 'Eine Bestätigungs-E-Mail wird an dich gesendet.', 'es' => 'Te enviaremos un correo de confirmación.', 'zh' => '系统将向您发送确认邮件。', 'ja' => '確認メールが送信されます。', 'pl' => 'Wyślemy Ci e-mail z potwierdzeniem.'],
    'account.password.current' => ['fr' => 'Mot de passe actuel', 'en' => 'Current password', 'de' => 'Aktuelles Passwort', 'es' => 'Contraseña actual', 'zh' => '当前密码', 'ja' => '現在のパスワード', 'pl' => 'Obecne hasło'],
    'account.password.new'  => ['fr' => 'Nouveau mot de passe', 'en' => 'New password', 'de' => 'Neues Passwort', 'es' => 'Nueva contraseña', 'zh' => '新密码', 'ja' => '新しいパスワード', 'pl' => 'Nowe hasło'],
    'account.password.help' => ['fr' => '8 caractères min · 1 lettre + 1 chiffre', 'en' => 'Min. 8 characters · 1 letter + 1 digit', 'de' => 'Min. 8 Zeichen · 1 Buchstabe + 1 Ziffer', 'es' => 'Mín. 8 caracteres · 1 letra + 1 dígito', 'zh' => '至少 8 位 · 1 个字母 + 1 个数字', 'ja' => '8文字以上 · 英字1つ + 数字1つ', 'pl' => 'Min. 8 znaków · 1 litera + 1 cyfra'],
    'account.password.confirm' => ['fr' => 'Confirmer', 'en' => 'Confirm', 'de' => 'Bestätigen', 'es' => 'Confirmar', 'zh' => '确认', 'ja' => '確認', 'pl' => 'Potwierdź'],
    'account.password.submit' => ['fr' => 'Modifier', 'en' => 'Update', 'de' => 'Ändern', 'es' => 'Modificar', 'zh' => '修改', 'ja' => '変更する', 'pl' => 'Zmień'],
    'account.export.title'  => ['fr' => 'Exporter mes données', 'en' => 'Export my data', 'de' => 'Meine Daten exportieren', 'es' => 'Exportar mis datos', 'zh' => '导出我的数据', 'ja' => 'データをエクスポート', 'pl' => 'Eksportuj moje dane'],
    'account.export.sub'    => ['fr' => 'Droit à la portabilité — format JSON.', 'en' => 'Right to data portability — JSON format.', 'de' => 'Recht auf Datenübertragbarkeit — JSON-Format.', 'es' => 'Derecho a la portabilidad — formato JSON.', 'zh' => '数据可携带权 —— JSON 格式。', 'ja' => 'データポータビリティの権利 — JSON形式。', 'pl' => 'Prawo do przenoszenia danych — format JSON.'],
    'account.export.desc'   => ['fr' => "Téléchargez l'ensemble de vos données personnelles : profil, consentements, inscriptions aux événements.", 'en' => 'Download all your personal data: profile, consents, event registrations.', 'de' => 'Lade all deine persönlichen Daten herunter: Profil, Einwilligungen, Veranstaltungsanmeldungen.', 'es' => 'Descarga todos tus datos personales: perfil, consentimientos, inscripciones a eventos.', 'zh' => '下载您的全部个人数据:资料、同意记录、活动报名。', 'ja' => 'すべての個人データ(プロフィール、同意記録、イベント登録)をダウンロードできます。', 'pl' => 'Pobierz wszystkie swoje dane osobowe: profil, zgody, rejestracje na wydarzenia.'],
    'account.export.btn'    => ['fr' => '📥 Télécharger (JSON)', 'en' => '📥 Download (JSON)', 'de' => '📥 Herunterladen (JSON)', 'es' => '📥 Descargar (JSON)', 'zh' => '📥 下载 (JSON)', 'ja' => '📥 ダウンロード (JSON)', 'pl' => '📥 Pobierz (JSON)'],
    'account.delete.title'  => ['fr' => 'Supprimer mon compte', 'en' => 'Delete my account', 'de' => 'Mein Konto löschen', 'es' => 'Eliminar mi cuenta', 'zh' => '删除我的账户', 'ja' => 'アカウントを削除', 'pl' => 'Usuń moje konto'],
    'account.delete.sub'    => ['fr' => "Droit à l'effacement (RGPD).", 'en' => 'Right to erasure (GDPR).', 'de' => 'Recht auf Löschung (DSGVO).', 'es' => 'Derecho de supresión (RGPD).', 'zh' => '删除权 (GDPR)。', 'ja' => '消去権利 (GDPR)。', 'pl' => 'Prawo do bycia zapomnianym (RODO).'],
    'account.delete.desc'   => ['fr' => 'Vos données personnelles seront anonymisées et votre compte désactivé. Les enregistrements comptables obligatoires sont conservés mais déliés de votre identité.', 'en' => 'Your personal data will be anonymised and your account disabled. Mandatory accounting records are kept but detached from your identity.', 'de' => 'Deine persönlichen Daten werden anonymisiert und dein Konto deaktiviert. Pflicht-Buchungsdaten werden aufbewahrt, aber von deiner Identität getrennt.', 'es' => 'Tus datos personales serán anonimizados y tu cuenta desactivada. Los registros contables obligatorios se conservan pero desvinculados de tu identidad.', 'zh' => '您的个人数据将被匿名化,账户将被停用。强制要求的会计记录会保留,但与您的身份脱钩。', 'ja' => '個人データは匿名化され、アカウントは無効化されます。法的に義務付けられた会計記録は保持されますが、あなたの身元とは切り離されます。', 'pl' => 'Twoje dane osobowe zostaną zanonimizowane, a konto dezaktywowane. Wymagane wpisy księgowe są zachowane, ale odłączone od Twojej tożsamości.'],
    'account.delete.btn'    => ['fr' => 'Supprimer mon compte', 'en' => 'Delete my account', 'de' => 'Mein Konto löschen', 'es' => 'Eliminar mi cuenta', 'zh' => '删除我的账户', 'ja' => 'アカウントを削除', 'pl' => 'Usuń moje konto'],
    'account.delete.zone'   => ['fr' => 'Zone sensible', 'en' => 'Sensitive area', 'de' => 'Sensibler Bereich', 'es' => 'Zona sensible', 'zh' => '敏感区域', 'ja' => '重要な操作', 'pl' => 'Strefa wrażliwa'],
    'account.delete.warning' => ['fr' => 'Cette action est irréversible', 'en' => 'This action is irreversible', 'de' => 'Diese Aktion ist unwiderruflich', 'es' => 'Esta acción es irreversible', 'zh' => '此操作不可撤销', 'ja' => 'この操作は取り消せません', 'pl' => 'Ta operacja jest nieodwracalna'],
    'account.delete.confirm.text' => ['fr' => 'Vous êtes sur le point de supprimer définitivement le compte {email}.', 'en' => 'You are about to permanently delete the account {email}.', 'de' => 'Du bist dabei, das Konto {email} dauerhaft zu löschen.', 'es' => 'Estás a punto de eliminar permanentemente la cuenta {email}.', 'zh' => '您即将永久删除账户 {email}。', 'ja' => 'アカウント {email} を完全に削除しようとしています。', 'pl' => 'Zaraz trwale usuniesz konto {email}.'],
    'account.delete.impact.profile' => ['fr' => 'Votre profil (nom, prénom, email, avatar)', 'en' => 'Your profile (last name, first name, email, avatar)', 'de' => 'Dein Profil (Name, Vorname, E-Mail, Avatar)', 'es' => 'Tu perfil (nombre, apellido, email, avatar)', 'zh' => '您的资料(姓名、邮箱、头像)', 'ja' => 'プロフィール(氏名、メール、アバター)', 'pl' => 'Twój profil (nazwisko, imię, e-mail, avatar)'],
    'account.delete.impact.registrations' => ['fr' => 'Vos inscriptions aux événements', 'en' => 'Your event registrations', 'de' => 'Deine Veranstaltungsanmeldungen', 'es' => 'Tus inscripciones a eventos', 'zh' => '您的活动报名', 'ja' => 'イベントへの登録', 'pl' => 'Twoje rejestracje na wydarzenia'],
    'account.delete.impact.consents' => ['fr' => 'Vos consentements RGPD', 'en' => 'Your GDPR consents', 'de' => 'Deine DSGVO-Einwilligungen', 'es' => 'Tus consentimientos RGPD', 'zh' => '您的 GDPR 同意记录', 'ja' => 'GDPRへの同意', 'pl' => 'Twoje zgody RODO'],
    'account.delete.impact.accounting' => ['fr' => 'Les données comptables sont conservées mais anonymisées', 'en' => 'Accounting data is kept but anonymised', 'de' => 'Buchungsdaten werden aufbewahrt, aber anonymisiert', 'es' => 'Los datos contables se conservan pero anonimizados', 'zh' => '会计数据保留但已匿名化', 'ja' => '会計データは保持されますが匿名化されます', 'pl' => 'Dane księgowe są zachowane, ale zanonimizowane'],
    'account.delete.type_confirm' => ['fr' => 'Tapez SUPPRIMER pour confirmer', 'en' => 'Type SUPPRIMER to confirm', 'de' => 'Tippe SUPPRIMER ein, um zu bestätigen', 'es' => 'Escribe SUPPRIMER para confirmar', 'zh' => '输入 SUPPRIMER 以确认', 'ja' => '確認するには SUPPRIMER と入力', 'pl' => 'Wpisz SUPPRIMER, aby potwierdzić'],
    'account.delete.btn.confirm' => ['fr' => '🗑️ Supprimer définitivement mon compte', 'en' => '🗑️ Permanently delete my account', 'de' => '🗑️ Mein Konto dauerhaft löschen', 'es' => '🗑️ Eliminar mi cuenta permanentemente', 'zh' => '🗑️ 永久删除我的账户', 'ja' => '🗑️ アカウントを完全に削除', 'pl' => '🗑️ Trwale usuń moje konto'],
    'account.delete.btn.keep' => ['fr' => '← Garder mon compte', 'en' => '← Keep my account', 'de' => '← Mein Konto behalten', 'es' => '← Conservar mi cuenta', 'zh' => '← 保留我的账户', 'ja' => '← アカウントを残す', 'pl' => '← Zachowaj moje konto'],

    /* ----------------------------------------------------------------- */
    /*  Espace élève (dashboard + inscriptions + layout)                 */
    /* ----------------------------------------------------------------- */
    'dash.eyebrow.member'   => ['fr' => 'Espace membre', 'en' => 'Member area', 'de' => 'Mitgliederbereich', 'es' => 'Zona de miembro', 'zh' => '会员专区', 'ja' => 'メンバーエリア', 'pl' => 'Strefa członka'],
    'dash.hello'            => ['fr' => 'Bonjour, {name} 👋', 'en' => 'Hello, {name} 👋', 'de' => 'Hallo, {name} 👋', 'es' => 'Hola, {name} 👋', 'zh' => '你好,{name} 👋', 'ja' => 'こんにちは、{name}さん 👋', 'pl' => 'Cześć, {name} 👋'],
    'dash.my_events'        => ['fr' => 'Mes prochains événements', 'en' => 'My upcoming events', 'de' => 'Meine nächsten Veranstaltungen', 'es' => 'Mis próximos eventos', 'zh' => '我的即将活动', 'ja' => '次のイベント', 'pl' => 'Moje nadchodzące wydarzenia'],
    'dash.no_registrations' => ['fr' => 'Aucune inscription à venir.', 'en' => 'No upcoming registrations.', 'de' => 'Keine anstehenden Anmeldungen.', 'es' => 'Ninguna inscripción próxima.', 'zh' => '暂无即将到来的报名。', 'ja' => '今後の登録はありません。', 'pl' => 'Brak nadchodzących rejestracji.'],
    'dash.view_registrations' => ['fr' => 'Voir mes inscriptions', 'en' => 'View my registrations', 'de' => 'Meine Anmeldungen ansehen', 'es' => 'Ver mis inscripciones', 'zh' => '查看我的报名', 'ja' => '登録一覧を見る', 'pl' => 'Zobacz moje rejestracje'],
    'dash.upcoming_aeic'    => ['fr' => 'Prochains événements AEIC', 'en' => 'Upcoming AEIC events', 'de' => 'Anstehende AEIC-Veranstaltungen', 'es' => 'Próximos eventos AEIC', 'zh' => '即将到来的 AEIC 活动', 'ja' => '今後のAEICイベント', 'pl' => 'Nadchodzące wydarzenia AEIC'],
    'dash.no_events'        => ['fr' => 'Aucun événement annoncé.', 'en' => 'No events announced.', 'de' => 'Keine Veranstaltungen angekündigt.', 'es' => 'Ningún evento anunciado.', 'zh' => '暂无公布的活动。', 'ja' => '告知されたイベントはありません。', 'pl' => 'Brak ogłoszonych wydarzeń.'],
    'dash.my_profile'       => ['fr' => 'Mon profil', 'en' => 'My profile', 'de' => 'Mein Profil', 'es' => 'Mi perfil', 'zh' => '我的资料', 'ja' => 'マイプロフィール', 'pl' => 'Mój profil'],
    'dash.menu.dashboard'   => ['fr' => 'Tableau de bord', 'en' => 'Dashboard', 'de' => 'Dashboard', 'es' => 'Panel', 'zh' => '仪表盘', 'ja' => 'ダッシュボード', 'pl' => 'Pulpit'],
    'dash.menu.inscriptions' => ['fr' => 'Mes inscriptions', 'en' => 'My registrations', 'de' => 'Meine Anmeldungen', 'es' => 'Mis inscripciones', 'zh' => '我的报名', 'ja' => '登録一覧', 'pl' => 'Moje rejestracje'],
    'dash.menu.profile'     => ['fr' => 'Mon profil', 'en' => 'My profile', 'de' => 'Mein Profil', 'es' => 'Mi perfil', 'zh' => '我的资料', 'ja' => 'マイプロフィール', 'pl' => 'Mój profil'],
    'dash.menu.data'        => ['fr' => 'Mes données (RGPD)', 'en' => 'My data (GDPR)', 'de' => 'Meine Daten (DSGVO)', 'es' => 'Mis datos (RGPD)', 'zh' => '我的数据 (GDPR)', 'ja' => 'マイデータ (GDPR)', 'pl' => 'Moje dane (RODO)'],
    'inscriptions.eyebrow'  => ['fr' => 'Événements', 'en' => 'Events', 'de' => 'Veranstaltungen', 'es' => 'Eventos', 'zh' => '活动', 'ja' => 'イベント', 'pl' => 'Wydarzenia'],
    'inscriptions.title'    => ['fr' => 'Mes inscriptions', 'en' => 'My registrations', 'de' => 'Meine Anmeldungen', 'es' => 'Mis inscripciones', 'zh' => '我的报名', 'ja' => '登録一覧', 'pl' => 'Moje rejestracje'],
    'inscriptions.empty'    => ['fr' => "Vous n'êtes inscrit·e à aucun événement pour le moment.", 'en' => 'You are not registered for any event yet.', 'de' => 'Du bist noch für keine Veranstaltung angemeldet.', 'es' => 'Aún no estás inscrito en ningún evento.', 'zh' => '您尚未报名任何活动。', 'ja' => 'まだイベントに登録されていません。', 'pl' => 'Nie jesteś jeszcze zapisany na żadne wydarzenie.'],
    'inscriptions.see_events' => ['fr' => 'Voir les événements', 'en' => 'See events', 'de' => 'Veranstaltungen ansehen', 'es' => 'Ver eventos', 'zh' => '查看活动', 'ja' => 'イベントを見る', 'pl' => 'Zobacz wydarzenia'],
    'inscriptions.col.event' => ['fr' => 'Événement', 'en' => 'Event', 'de' => 'Veranstaltung', 'es' => 'Evento', 'zh' => '活动', 'ja' => 'イベント', 'pl' => 'Wydarzenie'],
    'inscriptions.col.date' => ['fr' => 'Date', 'en' => 'Date', 'de' => 'Datum', 'es' => 'Fecha', 'zh' => '日期', 'ja' => '日付', 'pl' => 'Data'],
    'inscriptions.col.location' => ['fr' => 'Lieu', 'en' => 'Location', 'de' => 'Ort', 'es' => 'Lugar', 'zh' => '地点', 'ja' => '場所', 'pl' => 'Miejsce'],
    'inscriptions.col.status' => ['fr' => 'Statut', 'en' => 'Status', 'de' => 'Status', 'es' => 'Estado', 'zh' => '状态', 'ja' => '状態', 'pl' => 'Status'],
    'inscriptions.status.past' => ['fr' => 'Passé', 'en' => 'Past', 'de' => 'Vergangen', 'es' => 'Pasado', 'zh' => '已结束', 'ja' => '終了', 'pl' => 'Minione'],
    'inscriptions.status.upcoming' => ['fr' => 'À venir', 'en' => 'Upcoming', 'de' => 'Anstehend', 'es' => 'Próximo', 'zh' => '即将', 'ja' => '予定', 'pl' => 'Nadchodzące'],
    'profile.eyebrow'      => ['fr' => 'Compte', 'en' => 'Account', 'de' => 'Konto', 'es' => 'Cuenta', 'zh' => '账户', 'ja' => 'アカウント', 'pl' => 'Konto'],
    'profile.info'         => ['fr' => 'Informations', 'en' => 'Information', 'de' => 'Informationen', 'es' => 'Información', 'zh' => '信息', 'ja' => '情報', 'pl' => 'Informacje'],
    'profile.lastname'     => ['fr' => 'Nom', 'en' => 'Last name', 'de' => 'Nachname', 'es' => 'Apellidos', 'zh' => '姓氏', 'ja' => '姓', 'pl' => 'Nazwisko'],
    'profile.firstname'    => ['fr' => 'Prénom', 'en' => 'First name', 'de' => 'Vorname', 'es' => 'Nombre', 'zh' => '名字', 'ja' => '名', 'pl' => 'Imię'],
    'profile.password.change' => ['fr' => 'Changer de mot de passe', 'en' => 'Change password', 'de' => 'Passwort ändern', 'es' => 'Cambiar contraseña', 'zh' => '修改密码', 'ja' => 'パスワードを変更', 'pl' => 'Zmień hasło'],
    'profile.password.hint' => ['fr' => "Laissez vide pour ne pas changer. 8 car. min, une lettre et un chiffre.", 'en' => 'Leave blank to keep it. Min. 8 chars, one letter and one digit.', 'de' => 'Leer lassen, um es beizubehalten. Min. 8 Zeichen, ein Buchstabe und eine Ziffer.', 'es' => 'Déjalo en blanco para no cambiarlo. Mín. 8 caracteres, una letra y un dígito.', 'zh' => '留空则不修改。至少 8 位,包含一个字母和一个数字。', 'ja' => '変更しない場合は空欄のまま。8文字以上、英字1つと数字1つ。', 'pl' => 'Pozostaw puste, aby nie zmieniać. Min. 8 znaków, jedna litera i jedna cyfra.'],
    'profile.password.note' => ['fr' => "Le changement de mot de passe est optionnel : les champs informations (prénom, nom, e-mail) sont mis à jour séparément si vous laissez ces champs vides.", 'en' => 'Changing your password is optional: the information fields (first name, last name, email) are updated separately if you leave these fields blank.', 'de' => 'Die Passwortänderung ist optional: Die Informationsfelder (Vorname, Nachname, E-Mail) werden separat aktualisiert, wenn du diese Felder leer lässt.', 'es' => 'El cambio de contraseña es opcional: los campos de información (nombre, apellido, email) se actualizan por separado si dejas estos campos vacíos.', 'zh' => '修改密码为可选:若这些字段留空,信息字段(名字、姓氏、邮箱)将单独更新。', 'ja' => 'パスワードの変更は任意です。これらのフィールドが空の場合、情報欄(氏名、メール)は別々に更新されます。', 'pl' => 'Zmiana hasła jest opcjonalna: pola informacji (imię, nazwisko, e-mail) są aktualizowane osobno, jeśli zostawisz te pola puste.'],
    'profile.password.confirm_new' => ['fr' => 'Confirmer le nouveau mot de passe', 'en' => 'Confirm new password', 'de' => 'Neues Passwort bestätigen', 'es' => 'Confirmar nueva contraseña', 'zh' => '确认新密码', 'ja' => '新しいパスワードを確認', 'pl' => 'Potwierdź nowe hasło'],
    'profile.update'        => ['fr' => 'Mettre à jour', 'en' => 'Update', 'de' => 'Aktualisieren', 'es' => 'Actualizar', 'zh' => '更新', 'ja' => '更新する', 'pl' => 'Aktualizuj'],
    'password.new.title'   => ['fr' => 'Nouveau mot de passe', 'en' => 'New password', 'de' => 'Neues Passwort', 'es' => 'Nueva contraseña', 'zh' => '新密码', 'ja' => '新しいパスワード', 'pl' => 'Nowe hasło'],
    'password.reset.lead'  => ['fr' => 'Choisissez un nouveau mot de passe (8 caractères min, une lettre et un chiffre).', 'en' => 'Choose a new password (min. 8 characters, one letter and one digit).', 'de' => 'Wähle ein neues Passwort (min. 8 Zeichen, ein Buchstabe und eine Ziffer).', 'es' => 'Elige una nueva contraseña (mín. 8 caracteres, una letra y un dígito).', 'zh' => '设置新密码(至少 8 位,包含一个字母和一个数字)。', 'ja' => '新しいパスワードを設定(8文字以上、英字1つと数字1つ)。', 'pl' => 'Wybierz nowe hasło (min. 8 znaków, jedna litera i jedna cyfra).'],
    'password.reset.invalid' => ['fr' => 'Ce lien de réinitialisation est invalide.', 'en' => 'This reset link is invalid.', 'de' => 'Dieser Zurücksetzungslink ist ungültig.', 'es' => 'Este enlace de restablecimiento no es válido.', 'zh' => '此重置链接无效。', 'ja' => 'このリセットリンクは無効です。', 'pl' => 'Ten link do resetowania jest nieprawidłowy.'],
    'password.reset.request_link' => ['fr' => 'Demander un nouveau lien', 'en' => 'Request a new link', 'de' => 'Neuen Link anfordern', 'es' => 'Solicitar un nuevo enlace', 'zh' => '申请新链接', 'ja' => '新しいリンクを要求', 'pl' => 'Poproś o nowy link'],
    'password.confirm.label' => ['fr' => 'Confirmer le mot de passe', 'en' => 'Confirm password', 'de' => 'Passwort bestätigen', 'es' => 'Confirmar contraseña', 'zh' => '确认密码', 'ja' => 'パスワードを確認', 'pl' => 'Potwierdź hasło'],
    'password.reset.submit' => ['fr' => 'Réinitialiser', 'en' => 'Reset', 'de' => 'Zurücksetzen', 'es' => 'Restablecer', 'zh' => '重置', 'ja' => 'リセット', 'pl' => 'Resetuj'],
    'brand.sub'             => ['fr' => 'Étudiants · Calais', 'en' => 'Students · Calais', 'de' => 'Studierende · Calais', 'es' => 'Estudiantes · Calais', 'zh' => '学生 · 加来', 'ja' => '学生 · カレー', 'pl' => 'Studenci · Calais'],
    'brand.aria.home'       => ['fr' => '{name} — accueil', 'en' => '{name} — home', 'de' => '{name} — Startseite', 'es' => '{name} — inicio', 'zh' => '{name} — 首页', 'ja' => '{name} — ホーム', 'pl' => '{name} — strona główna'],
    'footer.association'    => ['fr' => 'Association Étudiante Informatique de Calais', 'en' => 'Student Computer Association of Calais', 'de' => 'Studierendenverein Informatik Calais', 'es' => 'Asociación Estudiantil de Informática de Calais', 'zh' => '加来计算机学生协会', 'ja' => 'カレー情報科学学生協会', 'pl' => 'Stowarzyszenie Studentów Informatyki w Calais'],

    /* ----------------------------------------------------------------- */
    /*  Paiement / événement (compléments)                               */
    /* ----------------------------------------------------------------- */
    'event.pay_online'      => ['fr' => 'Payer en ligne (SumUp)', 'en' => 'Pay online (SumUp)', 'de' => 'Online bezahlen (SumUp)', 'es' => 'Pagar en línea (SumUp)', 'zh' => '在线支付 (SumUp)', 'ja' => 'オンラインで支払う (SumUp)', 'pl' => 'Zapłać online (SumUp)'],

    /* ----------------------------------------------------------------- */
    /*  Pages CMS (placeholders hors contenu dynamique)                  */
    /* ----------------------------------------------------------------- */
    'page.placeholder'      => ['fr' => 'Contenu à venir.', 'en' => 'Content coming soon.', 'de' => 'Inhalt folgt.', 'es' => 'Contenido próximamente.', 'zh' => '内容即将上线。', 'ja' => 'コンテンツ準備中。', 'pl' => 'Treść wkrótce.'],
    'page.generic.eyebrow'  => ['fr' => 'Page', 'en' => 'Page', 'de' => 'Seite', 'es' => 'Página', 'zh' => '页面', 'ja' => 'ページ', 'pl' => 'Strona'],
    'page.legal.eyebrow'    => ['fr' => 'Informations légales', 'en' => 'Legal information', 'de' => 'Rechtliche Hinweise', 'es' => 'Información legal', 'zh' => '法律信息', 'ja' => '法的情報', 'pl' => 'Informacje prawne'],
    'page.legal.title'      => ['fr' => 'Mentions légales', 'en' => 'Legal notice', 'de' => 'Impressum', 'es' => 'Aviso legal', 'zh' => '法律声明', 'ja' => '法的記述', 'pl' => 'Informacje prawne'],
    'page.legal.placeholder' => ['fr' => "Contenu à venir. Les mentions légales seront publiées ici prochainement.", 'en' => 'Content coming soon. The legal notice will be published here shortly.', 'de' => 'Inhalt folgt. Das Impressum wird hier bald veröffentlicht.', 'es' => 'Contenido próximamente. El aviso legal se publicará aquí pronto.', 'zh' => '内容即将上线。法律声明将很快在此发布。', 'ja' => 'コンテンツ準備中。法的記述はまもなくここに公開されます。', 'pl' => 'Treść wkrótce. Informacje prawne zostaną tu wkrótce opublikowane.'],
    'page.legal.publisher'  => ['fr' => 'Éditeur du site', 'en' => 'Website publisher', 'de' => 'Herausgeber der Website', 'es' => 'Editor del sitio', 'zh' => '网站发布者', 'ja' => 'サイトの発行者', 'pl' => 'Wydawca strony'],
    'page.legal.publisher.desc' => ['fr' => 'AEIC — Association Étudiante Informatique de Calais.', 'en' => 'AEIC — Student Computer Association of Calais.', 'de' => 'AEIC — Studierendenverein Informatik Calais.', 'es' => 'AEIC — Asociación Estudiantil de Informática de Calais.', 'zh' => 'AEIC — 加来计算机学生协会。', 'ja' => 'AEIC — カレー情報科学学生協会。', 'pl' => 'AEIC — Stowarzyszenie Studentów Informatyki w Calais.'],
    'page.legal.publisher_responsible' => ['fr' => 'Responsable de publication', 'en' => 'Publication manager', 'de' => 'Verantwortlich für den Inhalt', 'es' => 'Responsable de publicación', 'zh' => '发布负责人', 'ja' => '発行責任者', 'pl' => 'Redaktor odpowiedzialny'],
    'page.legal.publisher_responsible.desc' => ['fr' => "Le bureau de l'AEIC.", 'en' => 'The AEIC board.', 'de' => 'Der AEIC-Vorstand.', 'es' => 'La junta de la AEIC.', 'zh' => 'AEIC 管理层。', 'ja' => 'AEICの役員。', 'pl' => 'Zarząd AEIC.'],
    'page.legal.hosting'    => ['fr' => 'Hébergement', 'en' => 'Hosting', 'de' => 'Hosting', 'es' => 'Alojamiento', 'zh' => '托管', 'ja' => 'ホスティング', 'pl' => 'Hosting'],
    'page.legal.hosting.desc' => ['fr' => 'Site hébergé sur un serveur dédié (VPS).', 'en' => 'Website hosted on a dedicated server (VPS).', 'de' => 'Website auf einem dedizierten Server (VPS) gehostet.', 'es' => 'Sitio alojado en un servidor dedicado (VPS).', 'zh' => '网站托管在专用服务器 (VPS) 上。', 'ja' => '専用サーバー (VPS) でホストされています。', 'pl' => 'Strona hostowana na serwerze dedykowanym (VPS).'],
    'page.privacy.eyebrow'  => ['fr' => 'RGPD · Confidentialité', 'en' => 'GDPR · Privacy', 'de' => 'DSGVO · Datenschutz', 'es' => 'RGPD · Privacidad', 'zh' => 'GDPR · 隐私', 'ja' => 'GDPR · プライバシー', 'pl' => 'RODO · Prywatność'],
    'page.privacy.title'    => ['fr' => 'Politique de confidentialité', 'en' => 'Privacy policy', 'de' => 'Datenschutzrichtlinie', 'es' => 'Política de privacidad', 'zh' => '隐私政策', 'ja' => 'プライバシーポリシー', 'pl' => 'Polityka prywatności'],
    'page.privacy.placeholder' => ['fr' => "Contenu à venir. La politique de confidentialité sera publiée ici prochainement.", 'en' => 'Content coming soon. The privacy policy will be published here shortly.', 'de' => 'Inhalt folgt. Die Datenschutzrichtlinie wird hier bald veröffentlicht.', 'es' => 'Contenido próximamente. La política de privacidad se publicará aquí pronto.', 'zh' => '内容即将上线。隐私政策将很快在此发布。', 'ja' => 'コンテンツ準備中。プライバシーポリシーはまもなくここに公開されます。', 'pl' => 'Treść wkrótce. Polityka prywatności zostanie tu wkrótce opublikowana.'],
    'page.privacy.collected' => ['fr' => 'Données collectées', 'en' => 'Data collected', 'de' => 'Erhobene Daten', 'es' => 'Datos recopilados', 'zh' => '收集的数据', 'ja' => '収集されるデータ', 'pl' => 'Zbierane dane'],
    'page.privacy.collected.desc' => ['fr' => "Nom, prénom, adresse e-mail, inscriptions aux événements et commandes cafétéria.", 'en' => 'Last name, first name, email address, event registrations and cafeteria orders.', 'de' => 'Name, Vorname, E-Mail-Adresse, Veranstaltungsanmeldungen und Cafeteria-Bestellungen.', 'es' => 'Nombre, apellido, correo electrónico, inscripciones a eventos y pedidos de cafetería.', 'zh' => '姓名、电子邮箱、活动报名和咖啡馆订单。', 'ja' => '氏名、メールアドレス、イベント登録、カフェテリアの注文。', 'pl' => 'Nazwisko, imię, adres e-mail, rejestracje na wydarzenia i zamówienia w kafeterii.'],
    'page.privacy.rights'   => ['fr' => 'Vos droits', 'en' => 'Your rights', 'de' => 'Deine Rechte', 'es' => 'Tus derechos', 'zh' => '您的权利', 'ja' => 'あなたの権利', 'pl' => 'Twoje prawa'],
    'page.privacy.rights.desc' => ['fr' => "Conformément au RGPD, vous disposez d'un droit d'accès, de rectification, d'effacement et d'opposition sur vos données.", 'en' => 'Under the GDPR, you have the right to access, rectify, erase and object to the processing of your data.', 'de' => 'Gemäß DSGVO hast du das Recht auf Auskunft, Berichtigung, Löschung und Widerspruch bezüglich deiner Daten.', 'es' => 'Conforme al RGPD, tienes derecho de acceso, rectificación, supresión y oposición sobre tus datos.', 'zh' => '根据 GDPR,您有权访问、更正、删除和反对处理您的数据。', 'ja' => 'GDPRに基づき、データへのアクセス、訂正、削除、処理への異議申し立ての権利があります。', 'pl' => 'Zgodnie z RODO masz prawo dostępu, sprostowania, usunięcia i sprzeciwu wobec przetwarzania swoich danych.'],
    'page.privacy.contact'  => ['fr' => 'Contact', 'en' => 'Contact', 'de' => 'Kontakt', 'es' => 'Contacto', 'zh' => '联系方式', 'ja' => 'お問い合わせ', 'pl' => 'Kontakt'],
    'page.privacy.contact.desc' => ['fr' => 'Pour toute demande :', 'en' => 'For any request:', 'de' => 'Für alle Anfragen:', 'es' => 'Para cualquier consulta:', 'zh' => '如有需求:', 'ja' => 'お問い合わせはこちら:', 'pl' => 'W sprawie wszelkich próśb:'],
    'page.cgu.eyebrow'      => ['fr' => "Conditions d'utilisation", 'en' => 'Terms of use', 'de' => 'Nutzungsbedingungen', 'es' => 'Condiciones de uso', 'zh' => '使用条款', 'ja' => '利用規約', 'pl' => 'Regulamin'],
    'page.cgu.title'        => ['fr' => 'CGU', 'en' => 'Terms', 'de' => 'AGB', 'es' => 'Términos', 'zh' => '条款', 'ja' => '利用規約', 'pl' => 'Regulamin'],
    'page.cgu.placeholder'  => ['fr' => "Contenu à venir. Les conditions d'utilisation seront publiées ici prochainement.", 'en' => "Content coming soon. The terms of use will be published here shortly.", 'de' => 'Inhalt folgt. Die Nutzungsbedingungen werden hier bald veröffentlicht.', 'es' => 'Contenido próximamente. Las condiciones de uso se publicarán aquí pronto.', 'zh' => '内容即将上线。使用条款将很快在此发布。', 'ja' => 'コンテンツ準備中。利用規約はまもなくここに公開されます。', 'pl' => 'Treść wkrótce. Regulamin zostanie tu wkrótce opublikowany.'],
    'page.cgu.object'       => ['fr' => 'Objet', 'en' => 'Purpose', 'de' => 'Gegenstand', 'es' => 'Objeto', 'zh' => '目的', 'ja' => '目的', 'pl' => 'Przedmiot'],
    'page.cgu.object.desc'  => ["fr" => "Les présentes conditions régissent l'utilisation du site de l'AEIC et de l'espace membre.", 'en' => 'These terms govern the use of the AEIC website and the member area.', 'de' => 'Diese Bedingungen regeln die Nutzung der AEIC-Website und des Mitgliederbereichs.', 'es' => 'Estas condiciones rigen el uso del sitio de la AEIC y de la zona de miembro.', 'zh' => '本条款适用于 AEIC 网站及会员专区的使用。', 'ja' => '本規約はAEICのサイトおよびメンバーエリアの利用を規定します。', 'pl' => 'Niniejszy regulamin reguluje korzystanie ze strony AEIC oraz strefy członka.'],
    'page.cgu.registration' => ['fr' => 'Inscription', 'en' => 'Registration', 'de' => 'Registrierung', 'es' => 'Inscripción', 'zh' => '注册', 'ja' => '登録', 'pl' => 'Rejestracja'],
    'page.cgu.registration.desc' => ['fr' => "L'inscription est réservée aux étudiants. Les informations fournies doivent être exactes.", 'en' => 'Registration is reserved for students. The information provided must be accurate.', 'de' => 'Die Registrierung ist Studierenden vorbehalten. Die angegebenen Informationen müssen korrekt sein.', 'es' => 'La inscripción está reservada a los estudiantes. La información proporcionada debe ser exacta.', 'zh' => '注册仅限学生。所提供的信息必须准确。', 'ja' => '登録は学生限定です。提供された情報は正確でなければなりません。', 'pl' => 'Rejestracja jest zarezerwowana dla studentów. Podane informacje muszą być dokładne.'],
    'page.cgu.responsibility' => ['fr' => 'Responsabilité', 'en' => 'Liability', 'de' => 'Haftung', 'es' => 'Responsabilidad', 'zh' => '责任', 'ja' => '責任', 'pl' => 'Odpowiedzialność'],
    'page.cgu.responsibility.desc' => ['fr' => "L'AEIC s'efforce de maintenir le site accessible mais ne saurait être tenue responsable des interruptions de service.", 'en' => 'The AEIC strives to keep the site accessible but cannot be held liable for service interruptions.', 'de' => 'Die AEIC bemüht sich, die Website zugänglich zu halten, haftet jedoch nicht für Dienstunterbrechungen.', 'es' => 'La AEIC se esfuerza por mantener el sitio accesible, pero no se hace responsable de las interrupciones del servicio.', 'zh' => 'AEIC 致力于保持网站可访问,但对服务中断不承担责任。', 'ja' => 'AEICはサイトのアクセス性維持に努めますが、サービス中断について責任を負いかねます。', 'pl' => 'AEIC dokłada starań, aby strona była dostępna, ale nie ponosi odpowiedzialności za przerwy w działaniu usługi.'],

    /* ----------------------------------------------------------------- */
    /*  Métadonnées de langues (pour le sélecteur)                       */
    /* ----------------------------------------------------------------- */
    'lang.fr' => ['fr' => 'Français', 'en' => 'French', 'de' => 'Französisch', 'es' => 'Francés', 'zh' => '法语', 'ja' => 'フランス語', 'pl' => 'Francuski'],
    'lang.en' => ['fr' => 'Anglais', 'en' => 'English', 'de' => 'Englisch', 'es' => 'Inglés', 'zh' => '英语', 'ja' => '英語', 'pl' => 'Angielski'],
    'lang.de' => ['fr' => 'Allemand', 'en' => 'German', 'de' => 'Deutsch', 'es' => 'Alemán', 'zh' => '德语', 'ja' => 'ドイツ語', 'pl' => 'Niemiecki'],
    'lang.es' => ['fr' => 'Espagnol', 'en' => 'Spanish', 'de' => 'Spanisch', 'es' => 'Español', 'zh' => '西班牙语', 'ja' => 'スペイン語', 'pl' => 'Hiszpański'],
    'lang.zh' => ['fr' => 'Chinois', 'en' => 'Chinese', 'de' => 'Chinesisch', 'es' => 'Chino', 'zh' => '中文', 'ja' => '中国語', 'pl' => 'Chiński'],
    'lang.ja' => ['fr' => 'Japonais', 'en' => 'Japanese', 'de' => 'Japanisch', 'es' => 'Japonés', 'zh' => '日语', 'ja' => '日本語', 'pl' => 'Japoński'],
    'lang.pl' => ['fr' => 'Polonais', 'en' => 'Polish', 'de' => 'Polnisch', 'es' => 'Polaco', 'zh' => '波兰语', 'ja' => 'ポーランド語', 'pl' => 'Polski'],

    /* ----------------------------------------------------------------- */
    /*  Catégories d'événements (traduisibles)                           */
    /* ----------------------------------------------------------------- */
    'cat.soiree'       => ['fr' => 'Soirée',        'en' => 'Party',          'de' => 'Party',           'es' => 'Fiesta',          'zh' => '晚会',     'ja' => 'パーティー',  'pl' => 'Impreza'],
    'cat.afterwork'    => ['fr' => 'Afterwork',     'en' => 'Afterwork',      'de' => 'Afterwork',       'es' => 'Afterwork',       'zh' => '课后聚会', 'ja' => 'アフターワーク','pl' => 'Afterwork'],
    'cat.barbecue'     => ['fr' => 'Barbecue',      'en' => 'Barbecue',       'de' => 'Grillfest',       'es' => 'Barbacoa',        'zh' => '烧烤',     'ja' => 'バーベキュー', 'pl' => 'Grill'],
    'cat.tournoi'      => ['fr' => 'Tournoi / LAN', 'en' => 'Tournament / LAN','de' => 'Turnier / LAN',  'es' => 'Torneo / LAN',    'zh' => '比赛/LAN',  'ja' => '大会/LAN',    'pl' => 'Turniej / LAN'],
    'cat.conference'   => ['fr' => 'Conférence',    'en' => 'Conference',     'de' => 'Konferenz',       'es' => 'Conferencia',     'zh' => '会议',     'ja' => 'カンファレンス','pl' => 'Konferencja'],
    'cat.sortie'       => ['fr' => 'Sortie',        'en' => 'Outing',         'de' => 'Ausflug',         'es' => 'Salida',          'zh' => '出游',     'ja' => '外出',       'pl' => 'Wyjście'],
    'cat.atelier'      => ['fr' => 'Atelier',       'en' => 'Workshop',       'de' => 'Workshop',        'es' => 'Taller',          'zh' => '工作坊',   'ja' => 'ワークショップ','pl' => 'Warsztat'],
    'cat.nuitinfo'     => ['fr' => 'Nuit de l\'Info','en' => 'Nuit de l\'Info','de' => 'Nuit de l\'Info', 'es' => 'Nuit de l\'Info', 'zh' => '信息之夜', 'ja' => 'Nuit de l\'Info','pl' => 'Nuit de l\'Info'],
    'cat.autre'        => ['fr' => 'Autre',         'en' => 'Other',          'de' => 'Sonstige',       'es' => 'Otro',            'zh' => '其他',     'ja' => 'その他',     'pl' => 'Inne'],
];
