-- AEIC — Mots Wordle en base de données
-- mysql -u aeic -p aeic < database/migrations/2026_wordle_words.sql
--
-- La sélection du mot du jour se fait côté PHP de façon déterministe :
-- tous les joueurs ont le même mot un jour donné, et aucun mot ne se
-- répète avant que toute la liste ne soit parcourue.

CREATE TABLE IF NOT EXISTS wordle_words (
    id          INT AUTO_INCREMENT PRIMARY KEY,
    word        VARCHAR(5) NOT NULL,
    language    ENUM('fr','en') NOT NULL,
    is_active   TINYINT(1) NOT NULL DEFAULT 1,
    created_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uniq_word_lang (word, language),
    KEY idx_lang_active (language, is_active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ===================== MOTS FRANÇAIS (5 lettres, sans accents) =====================
INSERT INTO wordle_words (word, language) VALUES
('TABLE','fr'),('CHIEN','fr'),('ARBRE','fr'),('FLEUR','fr'),('PLAGE','fr'),
('ROUTE','fr'),('PORTE','fr'),('AVION','fr'),('METRO','fr'),('ECOLE','fr'),
('LIVRE','fr'),('STYLO','fr'),('REGLE','fr'),('POMME','fr'),('CREPE','fr'),
('PIZZA','fr'),('ROUGE','fr'),('BLANC','fr'),('JAUNE','fr'),('MAUVE','fr'),
('GRAND','fr'),('PETIT','fr'),('CHAUD','fr'),('FROID','fr'),('LUNDI','fr'),
('MARDI','fr'),('MATIN','fr'),('PERES','fr'),('MERES','fr'),('FRERE','fr'),
('SOEUR','fr'),('ONCLE','fr'),('HEURE','fr'),('TEMPS','fr'),('VIEUX','fr'),
('JEUNE','fr'),('METAL','fr'),('VERRE','fr'),('NEIGE','fr'),('PLUIE','fr'),
('LOUPS','fr'),('LIONS','fr'),('SINGE','fr'),('MONDE','fr'),('TERRE','fr'),
('AIGLE','fr'),('LAPIN','fr'),('BLOND','fr'),('TROIS','fr'),('SAINT','fr'),
('FUMEE','fr'),('NUAGE','fr'),('ECRAN','fr'),('PIANO','fr'),('CARTE','fr'),
('TRAIN','fr'),('VOILE','fr'),('MOINE','fr'),('TOAST','fr'),('OMBRE','fr'),
('OURSE','fr'),('TIGRE','fr'),('GANTS','fr'),('COUPE','fr'),('SALLE','fr'),
('FOIRE','fr'),('CHENE','fr'),('CLAIR','fr'),('NOIRE','fr'),('BLEUE','fr'),
('POULE','fr'),('CRANE','fr'),('CRISE','fr'),('PECHE','fr'),('VASTE','fr'),
('LUTIN','fr'),('MAGIE','fr'),('NOYAU','fr'),('OASIS','fr'),('RAIES','fr'),
('RENNE','fr'),('SUITE','fr'),('TENTE','fr'),('USAGE','fr'),('VENTE','fr'),
('WAGON','fr'),('AILES','fr'),('AIMER','fr'),('BANDE','fr'),('BARBE','fr'),
('BETON','fr'),('BIBLE','fr'),('BIERE','fr'),('CABLE','fr'),('CHANT','fr'),
('CIRER','fr'),('CITER','fr'),('COLLE','fr'),('COMTE','fr'),('CORPS','fr'),
('COTON','fr'),('CRAIE','fr'),('CREME','fr'),('CROIX','fr'),('DAMES','fr'),
('DOUCE','fr'),('DOUZE','fr'),('ECHEC','fr'),('EFFET','fr'),('ENTRE','fr'),
('EPEES','fr'),('ESSAI','fr'),('ETAGE','fr'),('ETANG','fr'),('EVIER','fr'),
('FACON','fr'),('FAIRE','fr'),('FERME','fr'),('FINIR','fr'),('FLEAU','fr'),
('FORGE','fr'),('FOURS','fr'),('FRUIT','fr'),('FUTUR','fr'),('GAINS','fr'),
('GENIE','fr'),('GENRE','fr'),('GEOLE','fr'),('GLACE','fr'),('GOMME','fr'),
('GRACE','fr'),('GRAIN','fr'),('GRIVE','fr'),('HABIT','fr'),('HAUTE','fr'),
('HEROS','fr'),('IDEAL','fr'),('IGLOO','fr'),('IMAGE','fr'),('IMPOT','fr'),
('JETER','fr'),('JEUDI','fr'),('JOUER','fr'),('JOURS','fr'),('JANTE','fr'),
('LACET','fr'),('LAMPE','fr'),('LARGE','fr'),('LISTE','fr'),('LOUPE','fr'),
('LYCEE','fr'),('MALIN','fr'),('MAMAN','fr'),('MINCE','fr'),('MOTIF','fr'),
('MUSEE','fr'),('NUITS','fr'),('OCEAN','fr'),('OFFRE','fr'),('PAINS','fr'),
('PANNE','fr'),('PARCS','fr'),('PARIS','fr'),('PASSE','fr'),('PATIN','fr'),
('PERDU','fr'),('PHARE','fr'),('PIECE','fr'),('PILES','fr'),('PILON','fr'),
('PINCE','fr'),('PIPES','fr'),('PISTE','fr'),('PIVOT','fr'),('PLANS','fr'),
('PLATE','fr'),('PLOMB','fr'),('PLUME','fr'),('POELE','fr'),('POEME','fr'),
('POIRE','fr'),('POLES','fr'),('POLIR','fr'),('PORES','fr'),('POSTE','fr'),
('PREAU','fr'),('PRIME','fr'),('PRISE','fr'),('PRIVE','fr'),('RADIO','fr'),
('RAILS','fr'),('RAMES','fr'),('RANGS','fr'),('RECIT','fr'),('REINE','fr'),
('REPOS','fr'),('RIDER','fr'),('RIVET','fr'),('ROUES','fr'),('ROULE','fr'),
('RUGBY','fr'),('SABLE','fr'),('SAGES','fr'),('SALON','fr'),('SAUCE','fr'),
('SEMER','fr'),('SENTI','fr'),('SERFS','fr'),('SIGNE','fr'),('SOIRS','fr'),
('SORTS','fr'),('STADE','fr'),('SUCRE','fr'),('TANTE','fr'),('TAPIS','fr'),
('TARIF','fr'),('TENIR','fr'),('TERNE','fr'),('TIRER','fr'),('TOILE','fr'),
('TOITS','fr'),('TORDS','fr'),('TORSE','fr'),('TOUTE','fr'),('TRACE','fr'),
('TRAIT','fr'),('TROUE','fr'),('TROUS','fr'),('VAGUE','fr'),('VENIR','fr'),
('VENTS','fr'),('VERRA','fr'),('VIGNE','fr'),('VISER','fr'),('VIVRE','fr'),
('VRAIE','fr')
ON DUPLICATE KEY UPDATE word = VALUES(word);

-- ===================== MOTS ANGLAIS (5 letters) =====================
INSERT INTO wordle_words (word, language) VALUES
('HOUSE','en'),('TABLE','en'),('WATER','en'),('BREAD','en'),('APPLE','en'),
('CHAIR','en'),('MOUSE','en'),('LIGHT','en'),('NIGHT','en'),('MUSIC','en'),
('RIVER','en'),('OCEAN','en'),('CLOUD','en'),('STORM','en'),('BEACH','en'),
('FIELD','en'),('TOWER','en'),('TRAIN','en'),('PLANE','en'),('TRUCK','en'),
('CLASS','en'),('BOOKS','en'),('PAPER','en'),('STUDY','en'),('TEACH','en'),
('LEARN','en'),('WRITE','en'),('GRAPE','en'),('LEMON','en'),('MANGO','en'),
('PEACH','en'),('MELON','en'),('BERRY','en'),('SALAD','en'),('ONION','en'),
('BEANS','en'),('JUICE','en'),('CANDY','en'),('SUGAR','en'),('COLOR','en'),
('GREEN','en'),('BLACK','en'),('WHITE','en'),('BROWN','en'),('HAPPY','en'),
('BRAVE','en'),('PROUD','en'),('QUIET','en'),('SMART','en'),('FUNNY','en'),
('DREAM','en'),('PARTY','en'),('MAGIC','en'),('EARTH','en'),('HEART','en'),
('SMILE','en'),('PHONE','en'),('BRAIN','en'),('BONES','en'),('SKINS','en'),
('PRICE','en'),('STORE','en'),('TRADE','en'),('DEALS','en'),('SALES','en'),
('TAXES','en'),('CYBER','en'),('PIXEL','en'),('CODES','en'),('BYTES','en'),
('FILES','en'),('INPUT','en'),('CLICK','en'),('VIEWS','en'),('WORDS','en'),
('LINES','en'),('GAMES','en'),('CARDS','en'),('BOARD','en'),('SPORT','en'),
('GOALS','en'),('CHESS','en'),('TEAMS','en'),('SHARK','en'),('WHALE','en'),
('HORSE','en'),('SHEEP','en'),('EAGLE','en'),('SNAKE','en'),('ZEBRA','en'),
('PANDA','en'),('SUNNY','en'),('FOGGY','en'),('FROST','en'),('TIGER','en'),
('STEEL','en'),('STONE','en'),('BRICK','en'),('GLASS','en'),('METAL','en'),
('MONEY','en'),('WORLD','en'),('MONTH','en'),('WEEKS','en'),('CHILD','en'),
('GHOST','en'),('BLOOM','en'),('CROWN','en'),('SWORD','en'),('KNEEL','en'),
('FRUIT','en'),('BAKER','en'),('DANCE','en'),('DRINK','en'),('EATEN','en'),
('FAITH','en'),('FLOCK','en'),('GIANT','en'),('GLOBE','en'),('GRACE','en'),
('HEAVY','en'),('IVORY','en'),('JEANS','en'),('JOKER','en'),('KINGS','en'),
('KNIFE','en'),('LATER','en'),('LIVER','en'),('LUCKY','en'),('MERRY','en'),
('MOVIE','en'),('NEVER','en'),('NOBLE','en'),('OPENS','en'),('PEACE','en'),
('PRINT','en'),('QUICK','en'),('RADIO','en'),('ROBIN','en'),('ROYAL','en'),
('SALTY','en'),('SCARE','en'),('SHINY','en'),('SOLID','en'),('SOUTH','en'),
('SPICE','en'),('SPINE','en'),('STAFF','en'),('STAND','en'),('STORY','en'),
('SWEEP','en'),('SWING','en'),('TASTE','en'),('TEETH','en'),('THANK','en'),
('THEME','en'),('THICK','en'),('THORN','en'),('THREE','en'),('TIRED','en'),
('TODAY','en'),('TOPIC','en'),('TOTAL','en'),('TOUCH','en'),('TOXIC','en'),
('TRULY','en'),('TWICE','en'),('UNION','en'),('UPPER','en'),('URBAN','en'),
('VAPOR','en'),('VIDEO','en'),('VITAL','en'),('VOCAL','en'),('WASTE','en'),
('WATCH','en'),('WHEAT','en'),('WHEEL','en'),('WHISK','en'),('WIDTH','en'),
('WORTH','en'),('YACHT','en'),('YOUNG','en'),('YOUTH','en'),('ALPHA','en'),
('ANGEL','en'),('BLAZE','en'),('BRISK','en'),('BUNCH','en'),('CHARM','en'),
('CHEEK','en'),('CLIFF','en'),('CRAFT','en'),('CRAWL','en'),('CRYPT','en'),
('DAISY','en'),('DEPTH','en'),('DIARY','en'),('DOZEN','en'),('DRAFT','en'),
('DRAMA','en'),('DRAWN','en'),('DRESS','en'),('DRIVE','en'),('DROWN','en'),
('DWELL','en'),('ELBOW','en'),('ELDER','en'),('ENEMY','en'),('ENTRY','en'),
('EQUIP','en'),('EVENT','en'),('EVERY','en'),('EXACT','en'),('EXIST','en'),
('EXTRA','en'),('FAIRY','en'),('FANCY','en'),('FIBER','en'),('FINER','en'),
('FLAME','en'),('FLASH','en'),('FLEET','en'),('FLESH','en'),('FLOAT','en'),
('FLOOD','en'),('FLOOR','en'),('FLOUR','en'),('FOCUS','en'),('FORCE','en'),
('FORGE','en'),('FORTE','en'),('FOUND','en'),('FRAME','en'),('FRESH','en'),
('FRONT','en'),('FROZE','en'),('GHOST','en'),('GLORY','en'),('GRACE','en'),
('GUARD','en'),('GUEST','en'),('GUIDE','en'),('GUILT','en'),('HAPPY','en')
ON DUPLICATE KEY UPDATE word = VALUES(word);
